import type { IncomingMessage, ServerResponse } from "node:http";
import type { MobileGraphQLRequest } from "@rivonclaw/core";
import { executeMobileGraphQL } from "../mobile/mobile-graphql.js";
import { getRpcClient } from "../gateway/rpc-client-ref.js";
import { PAIRING_CODE_TTL_MS } from "../store/mobile-manager.js";
import type { ApiContext } from "./api-context.js";
import { parseBody, sendJson } from "./route-utils.js";

export async function handleMobileChatRoutes(
  req: IncomingMessage,
  res: ServerResponse,
  url: URL,
  pathname: string,
  ctx: ApiContext,
): Promise<boolean> {
  // Mobile GraphQL endpoint (used by Panel's registerPairing)
  if (pathname === "/api/graphql/mobile" && req.method === "POST") {
    const body = (await parseBody(req)) as MobileGraphQLRequest;
    const result = await executeMobileGraphQL(body, ctx);
    sendJson(res, 200, result);
    return true;
  }

  if (!pathname.startsWith("/api/mobile/")) {
    return false; // Not handled here
  }

  // W16-A1: Generate Pairing Code
  if (pathname === "/api/mobile/pairing-code/generate" && req.method === "POST") {
    if (!ctx.mobileManager) {
      sendJson(res, 500, { error: "Mobile Manager not initialized" });
      return true;
    }

    try {
      const codeData = await ctx.mobileManager.requestPairingCode();
      sendJson(res, 200, { ...codeData, ttlMs: PAIRING_CODE_TTL_MS });
    } catch (err: any) {
      sendJson(res, 500, { error: err.message || "Failed to generate pairing code" });
    }
    return true;
  }

  // Two-step pairing: get PWA install URL (Step 1, no pairing code needed)
  if (pathname === "/api/mobile/install-url" && req.method === "GET") {
    if (!ctx.mobileManager) {
      sendJson(res, 500, { error: "Mobile Manager not initialized" });
      return true;
    }

    try {
      const result = await ctx.mobileManager.getInstallUrl();
      sendJson(res, 200, result);
    } catch (err: any) {
      sendJson(res, 500, { error: err.message || "Failed to get install URL" });
    }
    return true;
  }

  // W16-A1: Get Pairing Status (returns all pairings)
  if (pathname === "/api/mobile/status" && req.method === "GET") {
    if (!ctx.mobileManager) {
      sendJson(res, 500, { error: "Mobile Manager not initialized" });
      return true;
    }

    const activeCode = ctx.mobileManager.getActiveCode();
    const pairings = ctx.mobileManager.root.mobilePairings.slice();

    // If a code generated by Desktop is awaiting mobile pairing, poll the Control Plane
    if (activeCode) {
      ctx.mobileManager
        .pollPairingStatus(activeCode.code)
        .then(
          (
            status: {
              paired: boolean;
              accessToken?: string;
              relayUrl?: string;
              pairingId?: string;
              desktopDeviceId?: string;
              mobileDeviceId?: string;
            } | null,
          ) => {
            if (status && status.paired && status.accessToken && status.relayUrl) {
              ctx.mobileManager!.completePairing(status as {
                accessToken: string;
                relayUrl: string;
                pairingId?: string;
                desktopDeviceId?: string;
                mobileDeviceId?: string;
              });
            }
          },
        )
        .catch((e: unknown) => console.error("Pairing wait failed", e));
    }

    sendJson(res, 200, {
      pairings,
      activeCode: activeCode || null,
      desktopDeviceId: ctx.mobileManager.getDesktopDeviceId(),
    });
    return true;
  }

  // Device-level presence status (relay connected + mobile online per device)
  if (pathname === "/api/mobile/device-status" && req.method === "GET") {
    // Lazy migration: re-key old mobileDeviceId-based allowlist entries to pairingId
    if (ctx.mobileManager) {
      ctx.mobileManager.runMigration();
    }

    const rpcClient = getRpcClient();
    if (!rpcClient?.isConnected()) {
      sendJson(res, 200, { devices: {} });
      return true;
    }

    try {
      const result = (await rpcClient.request("mobile_chat_device_status", {})) as {
        devices: Record<string, any>;
      };

      // Auto-persist stale status from plugin to DB
      const allPairings = ctx.mobileManager?.root.mobilePairings ?? [];
      for (const [pairingKey, status] of Object.entries(result.devices)) {
        if (status.stale) {
          const pairing = (allPairings as any[]).find(
            (p: any) => p.pairingId === pairingKey || p.id === pairingKey,
          );
          if (pairing && pairing.status !== "stale") {
            ctx.mobileManager?.markStale(pairing.id);
          }
        }
      }

      // Merge DB stale records (survives gateway restart)
      for (const p of allPairings as any[]) {
        const key = p.pairingId || p.id;
        if (p.status === "stale" && key && !result.devices[key]) {
          result.devices[key] = {
            relayConnected: false,
            mobileOnline: false,
            stale: true,
          };
        }
      }

      sendJson(res, 200, result);
    } catch (err: any) {
      // Even on RPC failure, return DB stale records
      const devices: Record<string, any> = {};
      try {
        const allPairings = ctx.mobileManager?.root.mobilePairings ?? [];
        for (const p of allPairings as any[]) {
          const key = p.pairingId || p.id;
          if (p.status === "stale" && key) {
            devices[key] = {
              relayConnected: false,
              mobileOnline: false,
              stale: true,
            };
          }
        }
      } catch {
        /* ignore */
      }
      sendJson(res, 200, { devices });
    }
    return true;
  }

  // W16-A1: Disconnect Pairing (specific or all)
  if (pathname === "/api/mobile/disconnect" && req.method === "DELETE") {
    if (!ctx.mobileManager) {
      sendJson(res, 500, { error: "Mobile Manager not initialized" });
      return true;
    }

    try {
      const pairingId = url.searchParams.get("pairingId") || undefined;
      if (pairingId) {
        ctx.mobileManager.removePairing(pairingId);
      } else {
        ctx.mobileManager.disconnectAll();
      }
      sendJson(res, 200, { success: true });
    } catch (err: any) {
      sendJson(res, 500, { error: err.message || "Failed to disconnect mobile pairing" });
    }
    return true;
  }

  return false;
}
