import { KNOWN_CHANNELS } from "../../lib/channel-defs.js";
import type { ChannelsStatusSnapshot, ChannelAccountSnapshot } from "../../api/index.js";

export function StatusBadge({ status, t }: { status: boolean | null | undefined; t: (key: string) => string }) {
  const variant = status === true ? "badge-success" : status === false ? "badge-danger" : "badge-warning";
  const text = status === true ? t("channels.statusYes") : status === false ? t("channels.statusNo") : t("channels.statusUnknown");

  return (
    <span className={`badge ${variant}`}>
      {text}
    </span>
  );
}

/** Return all known channels (no locale-based filtering). */
export function getVisibleChannels(_lang: string, _selectedDropdownChannel: string) {
  return [...KNOWN_CHANNELS];
}

export interface AccountEntry {
  channelId: string;
  channelLabel: string;
  account: ChannelAccountSnapshot;
}

/**
 * Minimal MST channel account shape consumed by `buildAccountsList`.
 * Declared structurally so the helper does not depend on mobx-state-tree
 * types (keeps this module pure and easy to unit-test).
 */
export interface MstChannelAccountLike {
  channelId: string;
  accountId: string;
  name: string | null;
  config: Record<string, unknown>;
}

/** Runtime status fields overlaid from the gateway snapshot. */
const RUNTIME_FIELDS = [
  "configured",
  "healthy",
  "enabled",
  "running",
  "linked",
  "connected",
  "reconnectAttempts",
  "lastConnectedAt",
  "lastError",
  "lastStartAt",
  "lastStopAt",
  "lastInboundAt",
  "lastOutboundAt",
  "lastProbeAt",
  "mode",
  "dmPolicy",
  "groupPolicy",
  "streamMode",
  "allowFrom",
  "tokenSource",
  "botTokenSource",
  "appTokenSource",
  "credentialSource",
  "audienceType",
  "audience",
  "webhookPath",
  "webhookUrl",
  "baseUrl",
  "allowUnmentionedGroups",
  "cliPath",
  "dbPath",
  "port",
  "probe",
  "audit",
  "application",
] as const;

/**
 * Build the unified accounts list.
 *
 * MST is the source of truth for which accounts exist and their identity
 * (channelId/accountId/name/config). The gateway snapshot is only used as
 * an overlay for runtime status fields (configured/healthy/enabled/running/
 * dmPolicy/tokenSource/…).
 *
 * Special case: **mobile** accounts do NOT live in `entityStore.channelAccounts` —
 * they live in `mobile_pairings` (SQLite) and are surfaced by the gateway in the
 * snapshot. For the `"mobile"` channelId we therefore fall back to the snapshot
 * directly. This is the one intentional exception to the MST-as-source-of-truth
 * rule; documented here so future refactors don't "clean it up" and break mobile.
 */
export function buildAccountsList(
  mstAccounts: ReadonlyArray<MstChannelAccountLike>,
  snapshot: ChannelsStatusSnapshot | null,
  t: (key: string) => string,
): AccountEntry[] {
  const allAccounts: AccountEntry[] = [];

  // ── Main path: iterate MST accounts, overlay runtime status from snapshot ──
  for (const mst of mstAccounts) {
    const { channelId, accountId } = mst;

    const knownChannel = KNOWN_CHANNELS.find(c => c.id === channelId);
    const channelLabel = knownChannel
      ? t(knownChannel.labelKey)
      : snapshot?.channelLabels[channelId] || channelId;

    const runtime = snapshot?.channelAccounts[channelId]?.find(a => a.accountId === accountId);

    const account: ChannelAccountSnapshot = runtime
      ? buildAccountWithRuntime(mst, runtime)
      : buildAccountWithoutRuntime(mst);

    allAccounts.push({ channelId, channelLabel, account });
  }

  // ── Mobile special case: accounts are not in MST, pull from snapshot ──
  const mobileAccounts = snapshot?.channelAccounts["mobile"] ?? [];
  if (mobileAccounts.length > 0) {
    const mobileChannel = KNOWN_CHANNELS.find(c => c.id === "mobile");
    const channelLabel = mobileChannel
      ? t(mobileChannel.labelKey)
      : snapshot?.channelLabels["mobile"] || "mobile";

    for (const account of mobileAccounts) {
      // Skip synthetic "default" placeholder accounts auto-generated by the
      // gateway when no mobile pairings exist yet.
      const isSyntheticDefault =
        account.accountId === "default" &&
        account.configured === false &&
        !account.name &&
        (account as { tokenSource?: string | null }).tokenSource === "none";

      if (isSyntheticDefault) continue;

      allAccounts.push({ channelId: "mobile", channelLabel, account });
    }
  }

  return allAccounts;
}

/**
 * Merge MST identity with the runtime overlay.
 * MST wins on identity (accountId, name). Runtime wins on status fields.
 * Config-derived fields from MST are used as a fallback when the runtime
 * overlay is missing them (e.g. dmPolicy/mode set in config but not yet
 * reflected in snapshot during a reload).
 */
function buildAccountWithRuntime(
  mst: MstChannelAccountLike,
  runtime: ChannelAccountSnapshot,
): ChannelAccountSnapshot {
  const merged: ChannelAccountSnapshot = {
    accountId: mst.accountId,
    name: mst.name ?? runtime.name ?? null,
  };

  for (const field of RUNTIME_FIELDS) {
    const runtimeValue = (runtime as Record<string, unknown>)[field];
    if (runtimeValue !== undefined) {
      (merged as Record<string, unknown>)[field] = runtimeValue;
    }
  }

  // Config-derived fallbacks for fields that may be absent from the runtime
  // overlay but are set in MST config (e.g. a freshly-saved account before
  // the gateway has re-probed).
  const cfg = mst.config;
  if (merged.dmPolicy == null && typeof cfg.dmPolicy === "string") merged.dmPolicy = cfg.dmPolicy;
  if (merged.groupPolicy == null && typeof cfg.groupPolicy === "string") merged.groupPolicy = cfg.groupPolicy;
  if (merged.streamMode == null && typeof cfg.streamMode === "string") merged.streamMode = cfg.streamMode;
  if (merged.mode == null && typeof cfg.mode === "string") merged.mode = cfg.mode;
  if (merged.webhookUrl == null && typeof cfg.webhookUrl === "string") merged.webhookUrl = cfg.webhookUrl;

  return merged;
}

/**
 * Build an entry from MST only (snapshot missing the account, e.g. gateway
 * not ready yet after startup or a restart).
 *
 * Conservative defaults per the refactor spec:
 * - `configured: true` — the account exists in MST, so it is configured
 * - `enabled: true` — unless the MST config explicitly says otherwise
 * - `healthy: null` — unknown, StatusBadge renders a neutral badge
 * - `running: null` — unknown, we cannot assert liveness without runtime data
 *
 * We explicitly do NOT optimistically report `running: true` — failing fast
 * with "unknown" is better than a stale green badge (see
 * `.claude/rules/development-philosophy.md` → Fail-Fast, Not Fail-Silent).
 */
function buildAccountWithoutRuntime(mst: MstChannelAccountLike): ChannelAccountSnapshot {
  const cfg = mst.config;
  const enabledFromConfig = typeof cfg.enabled === "boolean" ? cfg.enabled : true;

  const account: ChannelAccountSnapshot = {
    accountId: mst.accountId,
    name: mst.name,
    configured: true,
    enabled: enabledFromConfig,
    running: null,
    linked: null,
    connected: null,
  };

  if (typeof cfg.dmPolicy === "string") account.dmPolicy = cfg.dmPolicy;
  if (typeof cfg.groupPolicy === "string") account.groupPolicy = cfg.groupPolicy;
  if (typeof cfg.streamMode === "string") account.streamMode = cfg.streamMode;
  if (typeof cfg.mode === "string") account.mode = cfg.mode;
  if (typeof cfg.webhookUrl === "string") account.webhookUrl = cfg.webhookUrl;

  return account;
}
