const developerManagementFallback = {
  tableSearch: "Search BDs", showArchived: "Show archived", unassignedAccounts: "Unassigned accounts ({{count}})", managedCreators: "Creators", allRegions: "All regions", archivedStatus: "Archived", acceptingStatus: "Accepting", pausedStatus: "Paused", paginationSummary: "{{start}}-{{end}} of {{total}}", previousPage: "Previous page", nextPage: "Next page", noSearchResults: "No matching business developers", noSearchResultsHint: "Try a different name or clear the archived filter.", detailOverview: "Overview", noWorkingStyle: "No additional working instructions.", archiveBlockedHint: "Move all creators and outreach accounts before archiving this BD.", channelTransferHint: "Only accounts assigned to this BD are shown here. Use Transfer on an account when ownership needs to change.", transferAccount: "Transfer", transferTarget: "New responsible BD", transferTargetPlaceholder: "Choose a new owner", confirmTransfer: "Confirm transfer", detailTabsLabel: "BD workspace", channelsTab: "Outreach channels", settingsTab: "Work settings", unsavedChanges: "Unsaved changes", unsavedChangesConfirm: "Discard the unsaved BD settings and close?", unassignedAccountsTitle: "Unassigned outreach accounts", unassignedAccountsHint: "Assign each account to the BD who will use it for creator communication.", noUnassignedAccounts: "All outreach accounts are assigned.", preferredAccountSaved: "Preferred sender updated.", preferredAccount: "Preferred", makePreferred: "Make preferred", creatorContacts: "Creator contacts on these accounts", creatorContactsHint: "Each row is one concrete sender account → Creator contact route.", unknownContact: "Provider identity", unknownAccount: "Unavailable sender", noCreatorContacts: "No Creator contact has been added on this BD's accounts yet.",
} as const;

const operationalCopy = {
  en: {
    ...developerManagementFallback,
    globalApprovalPolicies: "Account-wide approval policies", globalApprovalPoliciesHint: "Applies to every Affiliate shop under this seller account. SEND_MESSAGE rules review the exact draft before provider delivery.", pageTabsLabel: "Team and safety sections", teamOperationsTab: "Team operations", safetyAndApprovalTab: "Safety & approvals",
    operationsOverview: "Affiliate operations overview", setupStatus: "Setup status", setupReady: "Ready for operations", setupRequired: "Review the AI boundary", humanDevelopers: "Human BDs", connectedChannels: "Outreach accounts", unassignedChannels: "{{count}} unassigned accounts", protectedCreators: "Protected creators", appliedProtections: "{{count}} matched to relationships",
    protectionBoundary: "AI operating boundary", protectionBoundaryReady: "The boundary is active. Add protected creators whenever your human team takes ownership of another relationship.", showProtectionManager: "Add protected creators", hideProtectionManager: "Close", addProtectionEntries: "Add protection entries", protectionEntryHint: "Enter each Creator's TikTok username, then optionally assign the responsible BD.", creatorIdentity: "Creator username", creatorIdentityPlaceholder: "@username", missingCreatorIdentity: "Provide creator_username.", assignProtectionDeveloper: "Human BD (optional)", protectionUnassigned: "No human BD (protection only)", removePreviewRow: "Remove row", templateField: "Field", templateRequirement: "Requirement", templateInstructions: "How to fill it", templateRequired: "Required", templateOptional: "Optional", templateIdentityRequired: "Required", templateIdentityHint: "Enter the Creator's TikTok username, with or without @.", templateDeveloperHint: "Enter the BD's exact display name from Team & channels. Leave blank for protection only. Do not enter a system ID.", templateNoteHint: "Optional reason or migration note.",
    responsibilityMap: "Responsibility map", responsibilityTitle: "Owners and outreach accounts", responsibilityHint: "Review BD workload, availability, and assigned outreach accounts.", ownerCount: "{{count}} BDs", ownerFilter: "Business developer", ownerSearchPlaceholder: "Search BDs by name", ownerChannelCount: "{{count}} accounts", unassignedOwner: "Unassigned", reconnectChannel: "Reconnect", emptyDevelopersTitle: "No business developers yet", emptyDevelopersHint: "Add a BD to manage their working preferences and outreach accounts. AI routing is configured separately from BD accounts.",
    tableSearch: "Search BDs", showArchived: "Show archived", unassignedAccounts: "Unassigned accounts ({{count}})", managedCreators: "Creators", allRegions: "All regions", archivedStatus: "Archived", acceptingStatus: "Accepting", pausedStatus: "Paused", paginationSummary: "{{start}}-{{end}} of {{total}}", previousPage: "Previous page", nextPage: "Next page", noSearchResults: "No matching business developers", noSearchResultsHint: "Try a different name or clear the archived filter.", detailOverview: "Overview", noWorkingStyle: "No additional working instructions.", archiveBlockedHint: "Move all creators and outreach accounts before archiving this BD.", channelTransferHint: "Only accounts assigned to this BD are shown here. Use Transfer on an account when ownership needs to change.", transferAccount: "Transfer", transferTarget: "New responsible BD", transferTargetPlaceholder: "Choose a new owner", confirmTransfer: "Confirm transfer", detailTabsLabel: "BD workspace", channelsTab: "Outreach channels", settingsTab: "Work settings", unsavedChanges: "Unsaved changes", unsavedChangesConfirm: "Discard the unsaved BD settings and close?", unassignedAccountsTitle: "Unassigned outreach accounts", unassignedAccountsHint: "Assign each account to the BD who will use it for creator communication.", noUnassignedAccounts: "All outreach accounts are assigned.",
  },
  zh: {
    ...developerManagementFallback,
    globalApprovalPolicies: "卖家账号全局审批规则", globalApprovalPoliciesHint: "适用于该卖家账号下所有 Affiliate 店铺。SEND_MESSAGE 规则会在 Provider 投递前审核准确的消息草稿。", pageTabsLabel: "团队与安全设置", teamOperationsTab: "团队运营", safetyAndApprovalTab: "安全与审批",
    operationsOverview: "Affiliate 运营概览", setupStatus: "设置状态", setupReady: "已可投入运营", setupRequired: "待确认 AI 边界", humanDevelopers: "人工 BD", connectedChannels: "联络账号", unassignedChannels: "{{count}} 个账号未分配", protectedCreators: "受保护达人", appliedProtections: "{{count}} 个已匹配达人关系",
    protectionBoundary: "AI 工作边界", protectionBoundaryReady: "保护边界已生效。人工团队接手新的达人关系时，仍可随时追加受保护达人。", showProtectionManager: "添加受保护达人", hideProtectionManager: "收起", addProtectionEntries: "添加保护记录", protectionEntryHint: "填写达人的 TikTok 用户名，并可选择负责这段关系的 BD。", creatorIdentity: "达人用户名", creatorIdentityPlaceholder: "@用户名", missingCreatorIdentity: "请填写 creator_username。", assignProtectionDeveloper: "负责人工 BD（可选）", protectionUnassigned: "暂不指定人工 BD（仅保护）", removePreviewRow: "移除这条记录", templateField: "字段", templateRequirement: "是否必填", templateInstructions: "填写说明", templateRequired: "必填", templateOptional: "可选", templateIdentityRequired: "必填", templateIdentityHint: "填写达人的 TikTok 用户名，带不带 @ 均可。", templateDeveloperHint: "填写“团队与渠道”页面中的 BD 完整显示名称；仅保护时留空。请勿填写系统 ID。", templateNoteHint: "可填写保护原因或迁移备注。",
    responsibilityMap: "责任分配", responsibilityTitle: "负责人和联络账号", responsibilityHint: "集中查看每位 BD 的工作负载、接收状态和名下联络账号。", ownerCount: "{{count}} 个 BD", ownerFilter: "商务开发", ownerSearchPlaceholder: "按姓名搜索 BD", ownerChannelCount: "{{count}} 个账号", unassignedOwner: "未分配负责人", reconnectChannel: "重新连接", emptyDevelopersTitle: "尚未添加商务开发", emptyDevelopersHint: "添加 BD 后可管理其工作指引与联络账号；AI 路由规则与 BD 账号分开配置。", preferredAccountSaved: "首选发件账号已更新。", preferredAccount: "首选账号", makePreferred: "设为首选", creatorContacts: "这些账号下的达人联系人", creatorContactsHint: "每一行代表一个明确的发件账号 → 达人联系方式。", unknownContact: "Provider 联系人", unknownAccount: "发件账号不可用", noCreatorContacts: "该 BD 的账号下尚未添加达人联系方式。",
    tableSearch: "搜索 BD", showArchived: "显示已归档", unassignedAccounts: "未分配账号（{{count}}）", managedCreators: "管理达人", allRegions: "全部地区", archivedStatus: "已归档", acceptingStatus: "接收中", pausedStatus: "已暂停", paginationSummary: "第 {{start}}-{{end}} 条，共 {{total}} 条", previousPage: "上一页", nextPage: "下一页", noSearchResults: "没有匹配的商务开发", noSearchResultsHint: "请尝试其他姓名，或调整归档筛选。", detailOverview: "概览", noWorkingStyle: "暂无额外工作指引。", archiveBlockedHint: "归档前需先转移该 BD 名下的达人和联络账号。", channelTransferHint: "这里只展示当前 BD 名下的联络账号；需要变更负责人时，可通过账号上的“转移”操作处理。", transferAccount: "转移", transferTarget: "新的负责 BD", transferTargetPlaceholder: "选择新的负责人", confirmTransfer: "确认转移", detailTabsLabel: "BD 工作区", channelsTab: "联络渠道", settingsTab: "工作设置", unsavedChanges: "有未保存修改", unsavedChangesConfirm: "工作设置尚未保存，确定放弃修改并关闭吗？", unassignedAccountsTitle: "未分配联络账号", unassignedAccountsHint: "请将账号分配给实际使用它与达人沟通的 BD。", noUnassignedAccounts: "所有联络账号均已分配。",
  },
  de: {
    globalApprovalPolicies: "Kontoweite Freigaberegeln", globalApprovalPoliciesHint: "Gilt für alle Affiliate-Shops dieses Verkäuferkontos. SEND_MESSAGE-Regeln prüfen den exakten Entwurf vor der Provider-Zustellung.", pageTabsLabel: "Team- und Sicherheitsbereiche", teamOperationsTab: "Teambetrieb", safetyAndApprovalTab: "Sicherheit & Freigaben",
    ...developerManagementFallback,
    operationsOverview: "Übersicht Affiliate-Betrieb", setupStatus: "Einrichtungsstatus", setupReady: "Betriebsbereit", setupRequired: "KI-Grenze prüfen", humanDevelopers: "Menschliche BDs", connectedChannels: "Kontaktkonten", unassignedChannels: "{{count}} nicht zugewiesene Konten", protectedCreators: "Geschützte Creator", appliedProtections: "{{count}} Beziehungen zugeordnet",
    protectionBoundary: "KI-Arbeitsgrenze", protectionBoundaryReady: "Die Grenze ist aktiv. Weitere vom Team übernommene Creator können jederzeit geschützt werden.", showProtectionManager: "Creator schützen", hideProtectionManager: "Schließen", addProtectionEntries: "Schutzeinträge hinzufügen", protectionEntryHint: "TikTok-Username eingeben und optional den zuständigen BD auswählen.", creatorIdentity: "Creator-Username", creatorIdentityPlaceholder: "@username", missingCreatorIdentity: "creator_username angeben.", assignProtectionDeveloper: "Menschlicher BD (optional)", protectionUnassigned: "Kein menschlicher BD (nur schützen)", removePreviewRow: "Zeile entfernen", templateField: "Feld", templateRequirement: "Anforderung", templateInstructions: "Ausfüllhinweis", templateRequired: "Erforderlich", templateOptional: "Optional", templateIdentityRequired: "Erforderlich", templateIdentityHint: "TikTok-Username des Creators mit oder ohne @ eingeben.", templateDeveloperHint: "Exakten Anzeigenamen des BD aus Team & Kanäle eingeben. Für reinen Schutz leer lassen. Keine System-ID eingeben.", templateNoteHint: "Optionaler Schutzgrund oder Migrationshinweis.",
    responsibilityMap: "Verantwortungsmatrix", responsibilityTitle: "Verantwortliche und Kontaktkonten", responsibilityHint: "BD auswählen, um Arbeitsmodus, Hinweise und Konten zu prüfen.", ownerCount: "{{count}} BDs", ownerFilter: "Business Developer", ownerSearchPlaceholder: "BD nach Namen suchen", ownerChannelCount: "{{count}} Konten", unassignedOwner: "Nicht zugewiesen", reconnectChannel: "Neu verbinden", emptyDevelopersTitle: "Noch keine Business Developer", emptyDevelopersHint: "Fügen Sie einen BD hinzu, um Arbeitsweise und Kontaktkonten zu verwalten. Die KI-Zuweisung wird separat von BD-Konten konfiguriert.",
  },
  es: {
    globalApprovalPolicies: "Reglas de aprobación de la cuenta", globalApprovalPoliciesHint: "Se aplica a todas las tiendas Affiliate de esta cuenta. Las reglas SEND_MESSAGE revisan el borrador exacto antes del envío.", pageTabsLabel: "Secciones de equipo y seguridad", teamOperationsTab: "Operaciones del equipo", safetyAndApprovalTab: "Seguridad y aprobaciones",
    ...developerManagementFallback,
    operationsOverview: "Resumen de operaciones", setupStatus: "Estado de configuración", setupReady: "Listo para operar", setupRequired: "Revisar el límite de IA", humanDevelopers: "BD humanos", connectedChannels: "Cuentas de contacto", unassignedChannels: "{{count}} cuentas sin asignar", protectedCreators: "Creadores protegidos", appliedProtections: "{{count}} relaciones vinculadas",
    protectionBoundary: "Límite operativo de IA", protectionBoundaryReady: "El límite está activo. Añade creadores protegidos cuando el equipo humano asuma otra relación.", showProtectionManager: "Añadir protegidos", hideProtectionManager: "Cerrar", addProtectionEntries: "Añadir protecciones", protectionEntryHint: "Introduce el usuario de TikTok y, si procede, el BD responsable.", creatorIdentity: "Usuario del creador", creatorIdentityPlaceholder: "@usuario", missingCreatorIdentity: "Indica creator_username.", assignProtectionDeveloper: "BD humano (opcional)", protectionUnassigned: "Sin BD humano (solo proteger)", removePreviewRow: "Eliminar fila", templateField: "Campo", templateRequirement: "Requisito", templateInstructions: "Cómo completarlo", templateRequired: "Obligatorio", templateOptional: "Opcional", templateIdentityRequired: "Obligatorio", templateIdentityHint: "Introduce el usuario de TikTok del creador, con o sin @.", templateDeveloperHint: "Introduce el nombre visible exacto del BD en Equipo y canales. Déjalo vacío para solo proteger. No uses un ID del sistema.", templateNoteHint: "Motivo de protección o nota de migración opcional.",
    responsibilityMap: "Mapa de responsabilidad", responsibilityTitle: "Responsables y cuentas de contacto", responsibilityHint: "Selecciona un BD para revisar su modo, instrucciones y cuentas.", ownerCount: "{{count}} BD", ownerFilter: "Business developer", ownerSearchPlaceholder: "Buscar BD por nombre", ownerChannelCount: "{{count}} cuentas", unassignedOwner: "Sin asignar", reconnectChannel: "Reconectar", emptyDevelopersTitle: "Aún no hay business developers", emptyDevelopersHint: "Añade un BD para gestionar sus instrucciones y cuentas de contacto. El enrutamiento de IA se configura por separado de las cuentas BD.",
  },
  fr: {
    globalApprovalPolicies: "Règles d’approbation du compte", globalApprovalPoliciesHint: "S’applique à toutes les boutiques Affiliate de ce compte vendeur. Les règles SEND_MESSAGE vérifient le brouillon exact avant l’envoi.", pageTabsLabel: "Sections équipe et sécurité", teamOperationsTab: "Opérations d’équipe", safetyAndApprovalTab: "Sécurité et approbations",
    ...developerManagementFallback,
    operationsOverview: "Vue des opérations", setupStatus: "État de configuration", setupReady: "Prêt à fonctionner", setupRequired: "Vérifier la limite IA", humanDevelopers: "BD humains", connectedChannels: "Comptes de contact", unassignedChannels: "{{count}} comptes non attribués", protectedCreators: "Créateurs protégés", appliedProtections: "{{count}} relations associées",
    protectionBoundary: "Limite d'action de l'IA", protectionBoundaryReady: "La limite est active. Ajoutez des créateurs protégés lorsque l'équipe humaine reprend une relation.", showProtectionManager: "Ajouter des protégés", hideProtectionManager: "Fermer", addProtectionEntries: "Ajouter des protections", protectionEntryHint: "Saisissez le nom d'utilisateur TikTok, puis éventuellement le BD responsable.", creatorIdentity: "Nom d'utilisateur du créateur", creatorIdentityPlaceholder: "@utilisateur", missingCreatorIdentity: "Indiquez creator_username.", assignProtectionDeveloper: "BD humain (facultatif)", protectionUnassigned: "Aucun BD humain (protection seule)", removePreviewRow: "Supprimer la ligne", templateField: "Champ", templateRequirement: "Exigence", templateInstructions: "Comment le remplir", templateRequired: "Obligatoire", templateOptional: "Facultatif", templateIdentityRequired: "Obligatoire", templateIdentityHint: "Saisissez le nom d'utilisateur TikTok du créateur, avec ou sans @.", templateDeveloperHint: "Saisissez le nom d'affichage exact du BD dans Équipe et canaux. Laissez vide pour protéger uniquement. N'utilisez pas d'ID système.", templateNoteHint: "Motif de protection ou note de migration facultative.",
    responsibilityMap: "Répartition des responsabilités", responsibilityTitle: "Responsables et comptes de contact", responsibilityHint: "Sélectionnez un BD pour consulter son mode, ses consignes et ses comptes.", ownerCount: "{{count}} BD", ownerFilter: "Business developer", ownerSearchPlaceholder: "Rechercher un BD par nom", ownerChannelCount: "{{count}} comptes", unassignedOwner: "Non attribué", reconnectChannel: "Reconnecter", emptyDevelopersTitle: "Aucun business developer", emptyDevelopersHint: "Ajoutez un BD pour gérer ses consignes et ses comptes. Le routage IA reste séparé des comptes BD.",
  },
  id: {
    globalApprovalPolicies: "Aturan persetujuan seluruh akun", globalApprovalPoliciesHint: "Berlaku untuk semua toko Affiliate di akun penjual ini. Aturan SEND_MESSAGE meninjau draf persis sebelum dikirim provider.", pageTabsLabel: "Bagian tim dan keamanan", teamOperationsTab: "Operasi tim", safetyAndApprovalTab: "Keamanan & persetujuan",
    ...developerManagementFallback,
    operationsOverview: "Ringkasan operasi afiliasi", setupStatus: "Status penyiapan", setupReady: "Siap beroperasi", setupRequired: "Tinjau batas AI", humanDevelopers: "BD manusia", connectedChannels: "Akun kontak", unassignedChannels: "{{count}} akun belum ditugaskan", protectedCreators: "Kreator terlindungi", appliedProtections: "{{count}} relasi cocok",
    protectionBoundary: "Batas kerja AI", protectionBoundaryReady: "Batas sudah aktif. Tambahkan kreator terlindungi saat tim manusia mengambil relasi baru.", showProtectionManager: "Tambah kreator terlindungi", hideProtectionManager: "Tutup", addProtectionEntries: "Tambah perlindungan", protectionEntryHint: "Masukkan username TikTok dan pilih BD bila diperlukan.", creatorIdentity: "Username kreator", creatorIdentityPlaceholder: "@username", missingCreatorIdentity: "Isi creator_username.", assignProtectionDeveloper: "BD manusia (opsional)", protectionUnassigned: "Tanpa BD manusia (hanya dilindungi)", removePreviewRow: "Hapus baris", templateField: "Kolom", templateRequirement: "Ketentuan", templateInstructions: "Cara mengisi", templateRequired: "Wajib", templateOptional: "Opsional", templateIdentityRequired: "Wajib", templateIdentityHint: "Masukkan username TikTok kreator, dengan atau tanpa @.", templateDeveloperHint: "Masukkan nama tampilan BD persis seperti di Tim & kanal. Kosongkan untuk hanya melindungi. Jangan masukkan ID sistem.", templateNoteHint: "Alasan perlindungan atau catatan migrasi opsional.",
    responsibilityMap: "Peta tanggung jawab", responsibilityTitle: "Penanggung jawab dan akun kontak", responsibilityHint: "Pilih BD untuk melihat mode kerja, instruksi, dan akun.", ownerCount: "{{count}} BD", ownerFilter: "Business developer", ownerSearchPlaceholder: "Cari BD berdasarkan nama", ownerChannelCount: "{{count}} akun", unassignedOwner: "Belum ditugaskan", reconnectChannel: "Hubungkan ulang", emptyDevelopersTitle: "Belum ada business developer", emptyDevelopersHint: "Tambahkan BD untuk mengelola instruksi kerja dan akun kontak. Perutean AI dikonfigurasi terpisah dari akun BD.",
  },
  it: {
    globalApprovalPolicies: "Regole di approvazione dell’account", globalApprovalPoliciesHint: "Si applica a tutti i negozi Affiliate dell’account venditore. Le regole SEND_MESSAGE verificano la bozza esatta prima dell’invio.", pageTabsLabel: "Sezioni team e sicurezza", teamOperationsTab: "Operazioni del team", safetyAndApprovalTab: "Sicurezza e approvazioni",
    ...developerManagementFallback,
    operationsOverview: "Panoramica operativa", setupStatus: "Stato configurazione", setupReady: "Pronto per operare", setupRequired: "Verifica il confine AI", humanDevelopers: "BD umani", connectedChannels: "Account di contatto", unassignedChannels: "{{count}} account non assegnati", protectedCreators: "Creator protetti", appliedProtections: "{{count}} relazioni associate",
    protectionBoundary: "Confine operativo AI", protectionBoundaryReady: "Il confine è attivo. Aggiungi creator protetti quando il team umano prende in carico nuove relazioni.", showProtectionManager: "Aggiungi protetti", hideProtectionManager: "Chiudi", addProtectionEntries: "Aggiungi protezioni", protectionEntryHint: "Inserisci lo username TikTok e, se necessario, assegna il BD.", creatorIdentity: "Username del creator", creatorIdentityPlaceholder: "@username", missingCreatorIdentity: "Inserisci creator_username.", assignProtectionDeveloper: "BD umano (facoltativo)", protectionUnassigned: "Nessun BD umano (solo protezione)", removePreviewRow: "Rimuovi riga", templateField: "Campo", templateRequirement: "Requisito", templateInstructions: "Come compilarlo", templateRequired: "Obbligatorio", templateOptional: "Facoltativo", templateIdentityRequired: "Obbligatorio", templateIdentityHint: "Inserisci lo username TikTok del creator, con o senza @.", templateDeveloperHint: "Inserisci il nome visualizzato esatto del BD in Team e canali. Lascia vuoto per la sola protezione. Non inserire un ID di sistema.", templateNoteHint: "Motivo della protezione o nota di migrazione facoltativa.",
    responsibilityMap: "Mappa delle responsabilità", responsibilityTitle: "Responsabili e account di contatto", responsibilityHint: "Seleziona un BD per vedere modalità, istruzioni e account.", ownerCount: "{{count}} BD", ownerFilter: "Business developer", ownerSearchPlaceholder: "Cerca BD per nome", ownerChannelCount: "{{count}} account", unassignedOwner: "Non assegnato", reconnectChannel: "Ricollega", emptyDevelopersTitle: "Nessun business developer", emptyDevelopersHint: "Aggiungi un BD per gestire istruzioni di lavoro e account di contatto. Il routing AI è configurato separatamente dagli account BD.",
  },
  th: {
    globalApprovalPolicies: "กฎอนุมัติทั้งบัญชี", globalApprovalPoliciesHint: "ใช้กับร้าน Affiliate ทุกแห่งในบัญชีผู้ขายนี้ กฎ SEND_MESSAGE จะตรวจร่างข้อความที่แน่นอนก่อนส่งผ่าน Provider", pageTabsLabel: "ส่วนทีมและความปลอดภัย", teamOperationsTab: "การดำเนินงานของทีม", safetyAndApprovalTab: "ความปลอดภัยและการอนุมัติ",
    ...developerManagementFallback,
    operationsOverview: "ภาพรวมงาน Affiliate", setupStatus: "สถานะการตั้งค่า", setupReady: "พร้อมใช้งาน", setupRequired: "ตรวจสอบขอบเขต AI", humanDevelopers: "BD ที่เป็นคน", connectedChannels: "บัญชีติดต่อ", unassignedChannels: "{{count}} บัญชียังไม่ได้มอบหมาย", protectedCreators: "ครีเอเตอร์ที่ปกป้อง", appliedProtections: "จับคู่แล้ว {{count}} ความสัมพันธ์",
    protectionBoundary: "ขอบเขตการทำงานของ AI", protectionBoundaryReady: "ขอบเขตมีผลแล้ว เพิ่มครีเอเตอร์ที่ปกป้องได้เมื่อทีมคนรับดูแลความสัมพันธ์ใหม่", showProtectionManager: "เพิ่มครีเอเตอร์ที่ปกป้อง", hideProtectionManager: "ปิด", addProtectionEntries: "เพิ่มรายการปกป้อง", protectionEntryHint: "กรอก username TikTok และเลือก BD ผู้รับผิดชอบได้", creatorIdentity: "Username ของครีเอเตอร์", creatorIdentityPlaceholder: "@username", missingCreatorIdentity: "กรอก creator_username", assignProtectionDeveloper: "BD ที่เป็นคน (ไม่บังคับ)", protectionUnassigned: "ไม่ระบุ BD ที่เป็นคน (ปกป้องเท่านั้น)", removePreviewRow: "ลบแถว", templateField: "ฟิลด์", templateRequirement: "ข้อกำหนด", templateInstructions: "วิธีกรอก", templateRequired: "จำเป็น", templateOptional: "ไม่บังคับ", templateIdentityRequired: "จำเป็น", templateIdentityHint: "กรอก username TikTok ของครีเอเตอร์ โดยมีหรือไม่มี @ ก็ได้", templateDeveloperHint: "กรอกชื่อที่แสดงของ BD ให้ตรงกับหน้า ทีมและช่องทาง เว้นว่างเมื่อต้องการปกป้องเท่านั้น ห้ามกรอก System ID", templateNoteHint: "เหตุผลในการปกป้องหรือบันทึกการย้ายข้อมูล (ไม่บังคับ)",
    responsibilityMap: "แผนผังผู้รับผิดชอบ", responsibilityTitle: "ผู้รับผิดชอบและบัญชีติดต่อ", responsibilityHint: "เลือก BD เพื่อดูโหมด คำแนะนำ และบัญชีที่ได้รับมอบหมาย", ownerCount: "BD {{count}} ราย", ownerFilter: "Business developer", ownerSearchPlaceholder: "ค้นหา BD ด้วยชื่อ", ownerChannelCount: "{{count}} บัญชี", unassignedOwner: "ยังไม่ได้มอบหมาย", reconnectChannel: "เชื่อมต่อใหม่", emptyDevelopersTitle: "ยังไม่มี business developer", emptyDevelopersHint: "เพิ่ม BD เพื่อจัดการคำแนะนำการทำงานและบัญชีติดต่อ โดยตั้งค่าการกำหนดเส้นทาง AI แยกจากบัญชี BD",
  },
} as const;

const protectionDirectoryCopy = {
  en: { protectionDirectorySummary: "{{resolved}} matched · {{unresolved}} waiting for identity", searchProtectedCreators: "Search username or OpenID", protectionResolved: "Matched Creator", protectionUnresolved: "Waiting for Creator identity", removeProtection: "Remove protection", removeProtectionConfirm: "Remove protection for {{creator}}? Existing work may become eligible for AI immediately.", protectionRemoved: "Protection removed", noProtectedCreators: "No protected Creators match this search.", allDevelopers: "All BDs" },
  zh: { protectionDirectorySummary: "{{resolved}} 个已匹配 · {{unresolved}} 个待识别", searchProtectedCreators: "搜索用户名或 OpenID", protectionResolved: "已匹配达人", protectionUnresolved: "等待达人身份", removeProtection: "移除保护", removeProtectionConfirm: "移除 {{creator}} 的保护？现有工作可能立即恢复 AI 派发。", protectionRemoved: "已移除保护", noProtectedCreators: "没有符合当前条件的受保护达人。", allDevelopers: "全部 BD" },
  de: { protectionDirectorySummary: "{{resolved}} zugeordnet · {{unresolved}} warten auf Identität", searchProtectedCreators: "Username oder OpenID suchen", protectionResolved: "Creator zugeordnet", protectionUnresolved: "Identität ausstehend", removeProtection: "Schutz entfernen", removeProtectionConfirm: "Schutz für {{creator}} entfernen? Bestehende Arbeit kann sofort wieder KI-fähig werden.", protectionRemoved: "Schutz entfernt", noProtectedCreators: "Keine passenden geschützten Creator.", allDevelopers: "Alle BDs" },
  es: { protectionDirectorySummary: "{{resolved}} vinculados · {{unresolved}} pendientes de identidad", searchProtectedCreators: "Buscar usuario u OpenID", protectionResolved: "Creador vinculado", protectionUnresolved: "Identidad pendiente", removeProtection: "Quitar protección", removeProtectionConfirm: "¿Quitar la protección de {{creator}}? El trabajo existente puede volver a ser elegible para IA.", protectionRemoved: "Protección eliminada", noProtectedCreators: "No hay creadores protegidos que coincidan.", allDevelopers: "Todos los BD" },
  fr: { protectionDirectorySummary: "{{resolved}} associés · {{unresolved}} en attente d’identité", searchProtectedCreators: "Rechercher un nom ou OpenID", protectionResolved: "Créateur associé", protectionUnresolved: "Identité en attente", removeProtection: "Retirer la protection", removeProtectionConfirm: "Retirer la protection de {{creator}} ? Le travail existant peut redevenir immédiatement éligible à l’IA.", protectionRemoved: "Protection retirée", noProtectedCreators: "Aucun créateur protégé correspondant.", allDevelopers: "Tous les BD" },
  id: { protectionDirectorySummary: "{{resolved}} cocok · {{unresolved}} menunggu identitas", searchProtectedCreators: "Cari username atau OpenID", protectionResolved: "Kreator cocok", protectionUnresolved: "Menunggu identitas", removeProtection: "Hapus perlindungan", removeProtectionConfirm: "Hapus perlindungan {{creator}}? Pekerjaan yang ada dapat langsung memenuhi syarat AI.", protectionRemoved: "Perlindungan dihapus", noProtectedCreators: "Tidak ada kreator terlindungi yang cocok.", allDevelopers: "Semua BD" },
  it: { protectionDirectorySummary: "{{resolved}} associati · {{unresolved}} in attesa di identità", searchProtectedCreators: "Cerca username o OpenID", protectionResolved: "Creator associato", protectionUnresolved: "Identità in attesa", removeProtection: "Rimuovi protezione", removeProtectionConfirm: "Rimuovere la protezione di {{creator}}? Il lavoro esistente può tornare subito idoneo per l’AI.", protectionRemoved: "Protezione rimossa", noProtectedCreators: "Nessun creator protetto corrispondente.", allDevelopers: "Tutti i BD" },
  th: { protectionDirectorySummary: "จับคู่แล้ว {{resolved}} · รอระบุตัวตน {{unresolved}}", searchProtectedCreators: "ค้นหาชื่อผู้ใช้หรือ OpenID", protectionResolved: "จับคู่ครีเอเตอร์แล้ว", protectionUnresolved: "รอระบุตัวตน", removeProtection: "ยกเลิกการปกป้อง", removeProtectionConfirm: "ยกเลิกการปกป้อง {{creator}} หรือไม่ งานเดิมอาจกลับไปเข้าเกณฑ์ AI ทันที", protectionRemoved: "ยกเลิกการปกป้องแล้ว", noProtectedCreators: "ไม่พบครีเอเตอร์ที่ปกป้องตามเงื่อนไข", allDevelopers: "BD ทั้งหมด" },
} as const;

const en = {
  eyebrow: "Affiliate operations", title: "Team & channels", subtitle: "Assign creator relationships and outreach accounts to the people responsible for moving them forward.",
  addDeveloper: "Add BD", aiTeam: "AI team", aiTeamHint: "Unassigned relationships", aiTeamDescription: "The AI team handles eligible creator relationships that are not assigned to a human BD.",
  businessDeveloper: "Business developer", virtualOwner: "Default owner", developerHint: "This BD's working mode and instructions apply to every assigned creator relationship.",
  roster: "Owners", workMode: "Work mode", aiAssisted: "AI assisted", humanOnly: "Human only", aiManaged: "AI managed", acceptingCreators: "Accepting new creators",
  whatsappAccounts: "WhatsApp accounts", emailAccounts: "Email accounts", channels: "Channels", connectChannel: "Connect channel", noChannels: "No outreach accounts are assigned to this owner.", unnamedAccount: "Unnamed account",
  workingStyle: "AI work guidance", workingStylePlaceholder: "Describe this BD's tone, priorities, negotiation boundaries, and escalation rules. This guidance is provided to the AI agent working for this BD.", regions: "Regions", name: "Name", newDeveloper: "New business developer", nameRequired: "Enter a BD name.", saved: "BD settings saved.",
  archive: "Archive", archiveConfirm: "Archive {{name}}? Reassign their creators and accounts first.", archived: "BD archived.", transferConfirm: "Move this account? Related creator channels will be rebound and pending work may be refreshed.", accountMoved: "Account owner updated.",
  onboardingStep: "Affiliate setup", onboardingTitle: "Protect existing BD relationships before AI starts", onboardingHint: "Import creators your current team already manages. Unlisted, unassigned relationships become eligible for the AI team after confirmation.",
  downloadTemplate: "Download template", importProtected: "Import protected creators", importPreview: "Import preview", importValid: "Import {{count}} valid rows", protectedOnly: "Protected only", ready: "Ready",
  assignDeveloper: "Responsible BD", note: "Note", notePlaceholder: "Why this relationship is protected", addProtectedCreator: "Add protected creator",
  emptySpreadsheet: "The spreadsheet has no readable worksheet.", duplicateCreator: "Duplicate creator in this file.", unknownDeveloper: "BD “{{name}}” does not exist.", protectionsImported: "Imported {{count}} protected creators.",
  confirmBoundary: "I reviewed the protected creator list. Relationships that are not protected and not assigned to a human BD may be handled by the AI team.", completeSetup: "Complete setup and enable AI", onboardingCompleted: "Affiliate operational setup completed.",
  ...operationalCopy.en, ...protectionDirectoryCopy.en,
} as const;

const zh = {
  eyebrow: "Affiliate 运营", title: "团队与渠道", subtitle: "把达人关系和联络渠道分配给真正负责推进合作的人。",
  addDeveloper: "新增 BD", aiTeam: "AI 团队", aiTeamHint: "未分配的达人关系", aiTeamDescription: "AI 团队负责所有未分配给人工 BD 且允许 AI 参与的达人关系。",
  businessDeveloper: "商务开发", virtualOwner: "默认负责人", developerHint: "该 BD 的工作模式和工作指引会作用于名下所有达人关系。",
  roster: "负责人", workMode: "工作模式", aiAssisted: "AI 辅助", humanOnly: "仅人工处理", aiManaged: "AI 管理", acceptingCreators: "接收新达人",
  whatsappAccounts: "WhatsApp 账号", emailAccounts: "邮箱账号", channels: "联络渠道", connectChannel: "连接渠道", noChannels: "该负责人尚未分配任何联络账号。", unnamedAccount: "未命名账号",
  workingStyle: "工作指引", workingStylePlaceholder: "填写该 BD 的沟通语气、业务重点、谈判边界和升级规则。这段内容会作为该 BD 的工作指导提供给 AI Agent。", regions: "负责地区", name: "姓名", newDeveloper: "新增商务开发", nameRequired: "请输入 BD 姓名。", saved: "BD 设置已保存。",
  archive: "归档", archiveConfirm: "归档 {{name}}？请先转移其达人关系和账号。", archived: "BD 已归档。", transferConfirm: "转移这个账号？相关达人渠道会重新归属，待处理工作也可能刷新。", accountMoved: "账号负责人已更新。",
  onboardingStep: "Affiliate 初始化", onboardingTitle: "在 AI 开始工作前保护现有 BD 关系", onboardingHint: "导入目前由人工团队维护的达人。确认后，未被保护且未分配人工 BD 的关系将由 AI 团队处理。",
  downloadTemplate: "下载模板", importProtected: "导入受保护达人", importPreview: "导入预览", importValid: "导入 {{count}} 条有效记录", protectedOnly: "仅保护", ready: "可导入",
  assignDeveloper: "负责 BD", note: "备注", notePlaceholder: "说明保护这段关系的原因", addProtectedCreator: "添加受保护达人",
  emptySpreadsheet: "表格中没有可读取的工作表。", duplicateCreator: "文件中达人重复。", unknownDeveloper: "BD“{{name}}”不存在。", protectionsImported: "已导入 {{count}} 个受保护达人。",
  confirmBoundary: "我已检查受保护达人名单；未被保护且未分配人工 BD 的达人关系可以由 AI 团队处理。", completeSetup: "完成设置并启用 AI", onboardingCompleted: "Affiliate 运营设置已完成。",
  ...operationalCopy.zh, ...protectionDirectoryCopy.zh,
} as const;

const de = {
  eyebrow: "Affiliate-Betrieb", title: "Team & Kanäle", subtitle: "Creator-Beziehungen und Kontaktkonten den zuständigen Personen zuweisen.", addDeveloper: "BD hinzufügen", aiTeam: "KI-Team", aiTeamHint: "Nicht zugewiesene Beziehungen", aiTeamDescription: "Das KI-Team bearbeitet geeignete Beziehungen ohne menschlichen BD.", businessDeveloper: "Business Developer", virtualOwner: "Standardverantwortlicher", developerHint: "Arbeitsmodus und Anweisungen gelten für alle zugewiesenen Creator.", roster: "Verantwortliche", workMode: "Arbeitsmodus", aiAssisted: "KI-unterstützt", humanOnly: "Nur manuell", aiManaged: "KI-verwaltet", acceptingCreators: "Nimmt neue Creator an", whatsappAccounts: "WhatsApp-Konten", emailAccounts: "E-Mail-Konten", channels: "Kanäle", connectChannel: "Kanal verbinden", noChannels: "Keine Kontaktkonten zugewiesen.", unnamedAccount: "Unbenanntes Konto", workingStyle: "KI-Arbeitsanweisung", workingStylePlaceholder: "Ton, Prioritäten, Verhandlungsgrenzen und Eskalationsregeln festlegen. Diese Anleitung wird dem KI-Agenten dieses BD bereitgestellt.", regions: "Regionen", name: "Name", newDeveloper: "Neuer Business Developer", nameRequired: "BD-Namen eingeben.", saved: "BD-Einstellungen gespeichert.", archive: "Archivieren", archiveConfirm: "{{name}} archivieren? Creator und Konten zuerst neu zuweisen.", archived: "BD archiviert.", transferConfirm: "Konto verschieben? Zugehörige Kanäle und offene Arbeit werden aktualisiert.", accountMoved: "Kontoinhaber aktualisiert.", onboardingStep: "Affiliate-Einrichtung", onboardingTitle: "Bestehende BD-Beziehungen vor dem KI-Start schützen", onboardingHint: "Bereits betreute Creator importieren. Andere nicht zugewiesene Beziehungen werden nach Bestätigung KI-fähig.", downloadTemplate: "Vorlage laden", importProtected: "Geschützte Creator importieren", importPreview: "Importvorschau", importValid: "{{count}} gültige Zeilen importieren", protectedOnly: "Nur geschützt", ready: "Bereit", assignDeveloper: "Zuständiger BD", note: "Notiz", notePlaceholder: "Grund für den Schutz", addProtectedCreator: "Creator schützen", emptySpreadsheet: "Keine lesbare Tabelle gefunden.", duplicateCreator: "Creator ist doppelt vorhanden.", unknownDeveloper: "BD „{{name}}“ existiert nicht.", protectionsImported: "{{count}} geschützte Creator importiert.", confirmBoundary: "Ich habe die Schutzliste geprüft. Nicht geschützte, nicht zugewiesene Beziehungen darf das KI-Team bearbeiten.", completeSetup: "Einrichtung abschließen und KI aktivieren", onboardingCompleted: "Affiliate-Einrichtung abgeschlossen.", ...operationalCopy.de, ...protectionDirectoryCopy.de,
} as const;

const es = {
  eyebrow: "Operaciones de afiliados", title: "Equipo y canales", subtitle: "Asigna relaciones y cuentas de contacto a las personas responsables.", addDeveloper: "Añadir BD", aiTeam: "Equipo de IA", aiTeamHint: "Relaciones sin asignar", aiTeamDescription: "El equipo de IA gestiona relaciones aptas sin un BD humano.", businessDeveloper: "Desarrollo de negocio", virtualOwner: "Responsable predeterminado", developerHint: "El modo y las instrucciones del BD se aplican a sus creadores.", roster: "Responsables", workMode: "Modo de trabajo", aiAssisted: "Asistido por IA", humanOnly: "Solo humano", aiManaged: "Gestionado por IA", acceptingCreators: "Acepta nuevos creadores", whatsappAccounts: "Cuentas de WhatsApp", emailAccounts: "Cuentas de correo", channels: "Canales", connectChannel: "Conectar canal", noChannels: "No hay cuentas asignadas.", unnamedAccount: "Cuenta sin nombre", workingStyle: "Estilo de trabajo", workingStylePlaceholder: "Describe tono, prioridades, negociación y traspasos.", regions: "Regiones", name: "Nombre", newDeveloper: "Nuevo BD", nameRequired: "Introduce el nombre del BD.", saved: "Configuración guardada.", archive: "Archivar", archiveConfirm: "¿Archivar a {{name}}? Reasigna antes sus creadores y cuentas.", archived: "BD archivado.", transferConfirm: "¿Mover esta cuenta? Se reasignarán canales y trabajos pendientes.", accountMoved: "Responsable actualizado.", onboardingStep: "Configuración de afiliados", onboardingTitle: "Protege relaciones existentes antes de activar la IA", onboardingHint: "Importa creadores ya gestionados. Los demás podrán pasar al equipo de IA.", downloadTemplate: "Descargar plantilla", importProtected: "Importar protegidos", importPreview: "Vista previa", importValid: "Importar {{count}} filas válidas", protectedOnly: "Solo protegido", ready: "Listo", assignDeveloper: "BD responsable", note: "Nota", notePlaceholder: "Motivo de protección", addProtectedCreator: "Proteger creador", emptySpreadsheet: "La hoja no contiene datos legibles.", duplicateCreator: "Creador duplicado.", unknownDeveloper: "El BD «{{name}}» no existe.", protectionsImported: "Se importaron {{count}} creadores protegidos.", confirmBoundary: "He revisado la lista. El equipo de IA puede gestionar relaciones no protegidas y sin BD humano.", completeSetup: "Completar y activar IA", onboardingCompleted: "Configuración completada.", ...operationalCopy.es, ...protectionDirectoryCopy.es,
} as const;

const fr = {
  eyebrow: "Opérations d'affiliation", title: "Équipe et canaux", subtitle: "Attribuez les relations et comptes de contact aux responsables.", addDeveloper: "Ajouter un BD", aiTeam: "Équipe IA", aiTeamHint: "Relations non attribuées", aiTeamDescription: "L'équipe IA gère les relations éligibles sans BD humain.", businessDeveloper: "Business developer", virtualOwner: "Responsable par défaut", developerHint: "Le mode et les consignes du BD s'appliquent à ses créateurs.", roster: "Responsables", workMode: "Mode de travail", aiAssisted: "Assisté par IA", humanOnly: "Humain uniquement", aiManaged: "Géré par IA", acceptingCreators: "Accepte de nouveaux créateurs", whatsappAccounts: "Comptes WhatsApp", emailAccounts: "Comptes e-mail", channels: "Canaux", connectChannel: "Connecter un canal", noChannels: "Aucun compte attribué.", unnamedAccount: "Compte sans nom", workingStyle: "Méthode de travail", workingStylePlaceholder: "Décrivez ton, priorités, négociation et transmission.", regions: "Régions", name: "Nom", newDeveloper: "Nouveau BD", nameRequired: "Saisissez le nom du BD.", saved: "Paramètres enregistrés.", archive: "Archiver", archiveConfirm: "Archiver {{name}} ? Réattribuez d'abord ses créateurs et comptes.", archived: "BD archivé.", transferConfirm: "Déplacer ce compte ? Les canaux et travaux associés seront actualisés.", accountMoved: "Responsable du compte mis à jour.", onboardingStep: "Configuration Affiliate", onboardingTitle: "Protégez les relations existantes avant l'IA", onboardingHint: "Importez les créateurs déjà suivis. Les autres pourront être gérés par l'équipe IA.", downloadTemplate: "Télécharger le modèle", importProtected: "Importer les créateurs protégés", importPreview: "Aperçu", importValid: "Importer {{count}} lignes valides", protectedOnly: "Protection seule", ready: "Prêt", assignDeveloper: "BD responsable", note: "Note", notePlaceholder: "Motif de protection", addProtectedCreator: "Protéger le créateur", emptySpreadsheet: "Aucune feuille lisible.", duplicateCreator: "Créateur en double.", unknownDeveloper: "Le BD « {{name}} » n'existe pas.", protectionsImported: "{{count}} créateurs protégés importés.", confirmBoundary: "J'ai vérifié la liste. L'équipe IA peut gérer les relations non protégées et sans BD humain.", completeSetup: "Terminer et activer l'IA", onboardingCompleted: "Configuration terminée.", ...operationalCopy.fr, ...protectionDirectoryCopy.fr,
} as const;

const id = {
  eyebrow: "Operasi afiliasi", title: "Tim & kanal", subtitle: "Tetapkan relasi kreator dan akun kontak kepada penanggung jawab.", addDeveloper: "Tambah BD", aiTeam: "Tim AI", aiTeamHint: "Relasi belum ditugaskan", aiTeamDescription: "Tim AI menangani relasi yang memenuhi syarat tanpa BD manusia.", businessDeveloper: "Business developer", virtualOwner: "Pemilik default", developerHint: "Mode dan instruksi BD berlaku untuk semua kreator yang ditugaskan.", roster: "Penanggung jawab", workMode: "Mode kerja", aiAssisted: "Dibantu AI", humanOnly: "Hanya manusia", aiManaged: "Dikelola AI", acceptingCreators: "Menerima kreator baru", whatsappAccounts: "Akun WhatsApp", emailAccounts: "Akun email", channels: "Kanal", connectChannel: "Hubungkan kanal", noChannels: "Belum ada akun yang ditugaskan.", unnamedAccount: "Akun tanpa nama", workingStyle: "Gaya kerja", workingStylePlaceholder: "Jelaskan nada, prioritas, negosiasi, dan serah terima.", regions: "Wilayah", name: "Nama", newDeveloper: "BD baru", nameRequired: "Masukkan nama BD.", saved: "Pengaturan tersimpan.", archive: "Arsipkan", archiveConfirm: "Arsipkan {{name}}? Pindahkan kreator dan akunnya dahulu.", archived: "BD diarsipkan.", transferConfirm: "Pindahkan akun ini? Kanal dan pekerjaan terkait akan diperbarui.", accountMoved: "Pemilik akun diperbarui.", onboardingStep: "Penyiapan afiliasi", onboardingTitle: "Lindungi relasi BD sebelum AI dimulai", onboardingHint: "Impor kreator yang sudah dikelola. Relasi lain dapat ditangani tim AI.", downloadTemplate: "Unduh templat", importProtected: "Impor kreator terlindungi", importPreview: "Pratinjau impor", importValid: "Impor {{count}} baris valid", protectedOnly: "Hanya dilindungi", ready: "Siap", assignDeveloper: "BD penanggung jawab", note: "Catatan", notePlaceholder: "Alasan perlindungan", addProtectedCreator: "Lindungi kreator", emptySpreadsheet: "Tidak ada lembar yang dapat dibaca.", duplicateCreator: "Kreator duplikat.", unknownDeveloper: "BD “{{name}}” tidak ada.", protectionsImported: "{{count}} kreator terlindungi diimpor.", confirmBoundary: "Saya telah meninjau daftar. Tim AI boleh menangani relasi yang tidak dilindungi dan tanpa BD manusia.", completeSetup: "Selesaikan dan aktifkan AI", onboardingCompleted: "Penyiapan selesai.", ...operationalCopy.id, ...protectionDirectoryCopy.id,
} as const;

const it = {
  eyebrow: "Operazioni affiliate", title: "Team e canali", subtitle: "Assegna relazioni e account di contatto ai responsabili.", addDeveloper: "Aggiungi BD", aiTeam: "Team AI", aiTeamHint: "Relazioni non assegnate", aiTeamDescription: "Il team AI gestisce le relazioni idonee senza BD umano.", businessDeveloper: "Business developer", virtualOwner: "Responsabile predefinito", developerHint: "Modalità e istruzioni del BD si applicano ai creator assegnati.", roster: "Responsabili", workMode: "Modalità di lavoro", aiAssisted: "Assistito da AI", humanOnly: "Solo umano", aiManaged: "Gestito da AI", acceptingCreators: "Accetta nuovi creator", whatsappAccounts: "Account WhatsApp", emailAccounts: "Account email", channels: "Canali", connectChannel: "Collega canale", noChannels: "Nessun account assegnato.", unnamedAccount: "Account senza nome", workingStyle: "Stile di lavoro", workingStylePlaceholder: "Descrivi tono, priorità, negoziazione e passaggi di consegna.", regions: "Regioni", name: "Nome", newDeveloper: "Nuovo BD", nameRequired: "Inserisci il nome del BD.", saved: "Impostazioni salvate.", archive: "Archivia", archiveConfirm: "Archiviare {{name}}? Riassegna prima creator e account.", archived: "BD archiviato.", transferConfirm: "Spostare questo account? Canali e lavori collegati verranno aggiornati.", accountMoved: "Responsabile aggiornato.", onboardingStep: "Configurazione affiliate", onboardingTitle: "Proteggi le relazioni esistenti prima dell'AI", onboardingHint: "Importa i creator già gestiti. Gli altri potranno essere gestiti dal team AI.", downloadTemplate: "Scarica modello", importProtected: "Importa creator protetti", importPreview: "Anteprima", importValid: "Importa {{count}} righe valide", protectedOnly: "Solo protetto", ready: "Pronto", assignDeveloper: "BD responsabile", note: "Nota", notePlaceholder: "Motivo della protezione", addProtectedCreator: "Proteggi creator", emptySpreadsheet: "Nessun foglio leggibile.", duplicateCreator: "Creator duplicato.", unknownDeveloper: "Il BD “{{name}}” non esiste.", protectionsImported: "Importati {{count}} creator protetti.", confirmBoundary: "Ho verificato l'elenco. Il team AI può gestire relazioni non protette e senza BD umano.", completeSetup: "Completa e attiva AI", onboardingCompleted: "Configurazione completata.", ...operationalCopy.it, ...protectionDirectoryCopy.it,
} as const;

const th = {
  eyebrow: "งาน Affiliate", title: "ทีมและช่องทาง", subtitle: "มอบหมายความสัมพันธ์และบัญชีติดต่อให้ผู้รับผิดชอบ", addDeveloper: "เพิ่ม BD", aiTeam: "ทีม AI", aiTeamHint: "ความสัมพันธ์ที่ยังไม่มอบหมาย", aiTeamDescription: "ทีม AI ดูแลความสัมพันธ์ที่เข้าเกณฑ์และไม่มี BD", businessDeveloper: "Business developer", virtualOwner: "ผู้รับผิดชอบเริ่มต้น", developerHint: "โหมดและคำแนะนำของ BD ใช้กับครีเอเตอร์ที่ได้รับมอบหมาย", roster: "ผู้รับผิดชอบ", workMode: "โหมดการทำงาน", aiAssisted: "AI ช่วยงาน", humanOnly: "คนดูแลเท่านั้น", aiManaged: "AI ดูแล", acceptingCreators: "รับครีเอเตอร์ใหม่", whatsappAccounts: "บัญชี WhatsApp", emailAccounts: "บัญชีอีเมล", channels: "ช่องทาง", connectChannel: "เชื่อมต่อช่องทาง", noChannels: "ยังไม่มีบัญชีที่มอบหมาย", unnamedAccount: "บัญชีไม่มีชื่อ", workingStyle: "รูปแบบการทำงาน", workingStylePlaceholder: "ระบุน้ำเสียง ลำดับความสำคัญ การเจรจา และการส่งต่องาน", regions: "ภูมิภาค", name: "ชื่อ", newDeveloper: "BD ใหม่", nameRequired: "กรุณาใส่ชื่อ BD", saved: "บันทึกแล้ว", archive: "เก็บถาวร", archiveConfirm: "เก็บ {{name}} หรือไม่ โปรดย้ายครีเอเตอร์และบัญชีก่อน", archived: "เก็บ BD แล้ว", transferConfirm: "ย้ายบัญชีนี้หรือไม่ ช่องทางและงานที่เกี่ยวข้องจะถูกรีเฟรช", accountMoved: "อัปเดตผู้รับผิดชอบแล้ว", onboardingStep: "ตั้งค่า Affiliate", onboardingTitle: "ปกป้องความสัมพันธ์เดิมก่อนเปิด AI", onboardingHint: "นำเข้าครีเอเตอร์ที่ทีมดูแลอยู่ ความสัมพันธ์อื่นสามารถให้ทีม AI ดูแลได้", downloadTemplate: "ดาวน์โหลดแม่แบบ", importProtected: "นำเข้าครีเอเตอร์ที่ปกป้อง", importPreview: "ตัวอย่างนำเข้า", importValid: "นำเข้า {{count}} แถว", protectedOnly: "ปกป้องเท่านั้น", ready: "พร้อม", assignDeveloper: "BD ผู้รับผิดชอบ", note: "หมายเหตุ", notePlaceholder: "เหตุผลที่ปกป้อง", addProtectedCreator: "เพิ่มครีเอเตอร์", emptySpreadsheet: "ไม่พบชีตที่อ่านได้", duplicateCreator: "ครีเอเตอร์ซ้ำ", unknownDeveloper: "ไม่พบ BD “{{name}}”", protectionsImported: "นำเข้า {{count}} ครีเอเตอร์แล้ว", confirmBoundary: "ฉันตรวจสอบรายชื่อแล้ว ทีม AI สามารถดูแลความสัมพันธ์ที่ไม่ถูกปกป้องและไม่มี BD ได้", completeSetup: "เสร็จสิ้นและเปิด AI", onboardingCompleted: "ตั้งค่าเสร็จแล้ว", ...operationalCopy.th, ...protectionDirectoryCopy.th,
} as const;

const deliveryAuditCopy = {
  en: { deliverySelection: { TRIGGER_CHANNEL: "Original channel", AGENT_OVERRIDE: "Channel override", RELATIONSHIP_DEFAULT: "Relationship default" }, deliveryAudit: "{{selection}} · selected {{preferred}} · actual {{actual}} · {{status}}", deliveryFailure: "Delivery failed: {{error}}" },
  zh: { deliverySelection: { TRIGGER_CHANNEL: "原渠道", AGENT_OVERRIDE: "Agent 切换渠道", RELATIONSHIP_DEFAULT: "关系默认渠道" }, deliveryAudit: "{{selection}} · 选定 {{preferred}} · 实际 {{actual}} · {{status}}", deliveryFailure: "投递失败：{{error}}" },
  de: { deliverySelection: { TRIGGER_CHANNEL: "Ursprungskanal", AGENT_OVERRIDE: "Kanalwechsel", RELATIONSHIP_DEFAULT: "Beziehungsstandard" }, deliveryAudit: "{{selection}} · gewählt {{preferred}} · tatsächlich {{actual}} · {{status}}", deliveryFailure: "Zustellung fehlgeschlagen: {{error}}" },
  es: { deliverySelection: { TRIGGER_CHANNEL: "Canal original", AGENT_OVERRIDE: "Cambio de canal", RELATIONSHIP_DEFAULT: "Canal predeterminado" }, deliveryAudit: "{{selection}} · seleccionado {{preferred}} · real {{actual}} · {{status}}", deliveryFailure: "Error de entrega: {{error}}" },
  fr: { deliverySelection: { TRIGGER_CHANNEL: "Canal d’origine", AGENT_OVERRIDE: "Changement de canal", RELATIONSHIP_DEFAULT: "Canal par défaut" }, deliveryAudit: "{{selection}} · choisi {{preferred}} · réel {{actual}} · {{status}}", deliveryFailure: "Échec de livraison : {{error}}" },
  id: { deliverySelection: { TRIGGER_CHANNEL: "Kanal asal", AGENT_OVERRIDE: "Penggantian kanal", RELATIONSHIP_DEFAULT: "Kanal default relasi" }, deliveryAudit: "{{selection}} · dipilih {{preferred}} · aktual {{actual}} · {{status}}", deliveryFailure: "Pengiriman gagal: {{error}}" },
  it: { deliverySelection: { TRIGGER_CHANNEL: "Canale originale", AGENT_OVERRIDE: "Cambio canale", RELATIONSHIP_DEFAULT: "Canale predefinito" }, deliveryAudit: "{{selection}} · selezionato {{preferred}} · effettivo {{actual}} · {{status}}", deliveryFailure: "Invio non riuscito: {{error}}" },
  th: { deliverySelection: { TRIGGER_CHANNEL: "ช่องทางเดิม", AGENT_OVERRIDE: "เปลี่ยนช่องทาง", RELATIONSHIP_DEFAULT: "ช่องทางเริ่มต้นของความสัมพันธ์" }, deliveryAudit: "{{selection}} · เลือก {{preferred}} · ใช้จริง {{actual}} · {{status}}", deliveryFailure: "ส่งข้อความไม่สำเร็จ: {{error}}" },
} as const;

const protectionWorkspaceCopy = {
  en: { relationshipProtectionChangeConfirm: "Change Creator protection? Removing protection may immediately resume AI dispatch for existing work.", protectionDispatchBlocked: "This Creator is protected. The work remains visible for staff, but AI dispatch is blocked." },
  zh: { relationshipProtectionChangeConfirm: "修改达人保护状态？移除保护后，现有工作可能立即恢复 AI 派发。", protectionDispatchBlocked: "该达人已受保护。人工仍可查看和处理工作，但系统不会派发给 AI。" },
  de: { relationshipProtectionChangeConfirm: "Creator-Schutz ändern? Nach dem Entfernen kann bestehende Arbeit sofort wieder an die KI gesendet werden.", protectionDispatchBlocked: "Dieser Creator ist geschützt. Die Arbeit bleibt für Mitarbeitende sichtbar, wird aber nicht an die KI gesendet." },
  es: { relationshipProtectionChangeConfirm: "¿Cambiar la protección? Al quitarla, el trabajo existente puede volver a enviarse a la IA de inmediato.", protectionDispatchBlocked: "Este creador está protegido. El trabajo sigue visible para el personal, pero no se envía a la IA." },
  fr: { relationshipProtectionChangeConfirm: "Modifier la protection ? Sa suppression peut relancer immédiatement l’envoi à l’IA pour le travail existant.", protectionDispatchBlocked: "Ce créateur est protégé. Le travail reste visible pour l’équipe, mais n’est pas envoyé à l’IA." },
  id: { relationshipProtectionChangeConfirm: "Ubah perlindungan kreator? Menghapusnya dapat langsung melanjutkan dispatch AI untuk pekerjaan yang ada.", protectionDispatchBlocked: "Kreator ini dilindungi. Pekerjaan tetap terlihat oleh staf, tetapi tidak dikirim ke AI." },
  it: { relationshipProtectionChangeConfirm: "Modificare la protezione? Rimuovendola, il lavoro esistente può tornare subito all’AI.", protectionDispatchBlocked: "Questo creator è protetto. Il lavoro resta visibile allo staff, ma non viene inviato all’AI." },
  th: { relationshipProtectionChangeConfirm: "เปลี่ยนสถานะการปกป้องหรือไม่ การยกเลิกอาจทำให้งานเดิมกลับไปถูกส่งให้ AI ทันที", protectionDispatchBlocked: "ครีเอเตอร์นี้ถูกปกป้อง งานยังแสดงให้พนักงานเห็น แต่จะไม่ถูกส่งให้ AI" },
} as const;

const protectionImportCopy = {
  en: { protectionImportProgress: "Importing {{completed}} / {{total}}", protectionImportPartialFailure: "Import stopped after {{completed}} / {{total}} rows. Completed rows are safe to retry. {{reason}}" },
  zh: { protectionImportProgress: "正在导入 {{completed}} / {{total}}", protectionImportPartialFailure: "导入在 {{completed}} / {{total}} 条后中断。已完成的记录可以安全重试。{{reason}}" },
  de: { protectionImportProgress: "{{completed}} / {{total}} werden importiert", protectionImportPartialFailure: "Der Import wurde nach {{completed}} / {{total}} Zeilen unterbrochen. Abgeschlossene Zeilen können sicher erneut importiert werden. {{reason}}" },
  es: { protectionImportProgress: "Importando {{completed}} / {{total}}", protectionImportPartialFailure: "La importación se detuvo tras {{completed}} / {{total}} filas. Las filas completadas se pueden reintentar con seguridad. {{reason}}" },
  fr: { protectionImportProgress: "Importation {{completed}} / {{total}}", protectionImportPartialFailure: "L’importation s’est arrêtée après {{completed}} / {{total}} lignes. Les lignes terminées peuvent être réessayées sans risque. {{reason}}" },
  id: { protectionImportProgress: "Mengimpor {{completed}} / {{total}}", protectionImportPartialFailure: "Impor berhenti setelah {{completed}} / {{total}} baris. Baris yang selesai aman untuk dicoba lagi. {{reason}}" },
  it: { protectionImportProgress: "Importazione {{completed}} / {{total}}", protectionImportPartialFailure: "L’importazione si è interrotta dopo {{completed}} / {{total}} righe. Le righe completate possono essere ritentate in sicurezza. {{reason}}" },
  th: { protectionImportProgress: "กำลังนำเข้า {{completed}} / {{total}}", protectionImportPartialFailure: "การนำเข้าหยุดหลังจาก {{completed}} / {{total}} แถว สามารถลองนำเข้าแถวที่เสร็จแล้วซ้ำได้อย่างปลอดภัย {{reason}}" },
} as const;

export const AFFILIATE_TEAM_TRANSLATIONS = {
  en: { nav: { affiliateTeam: "Team & channels" }, ecommerce: { affiliateTeam: { ...en, ...protectionImportCopy.en }, affiliateWorkspace: { ...deliveryAuditCopy.en, ...protectionWorkspaceCopy.en, relationshipOwner: "Relationship owner", relationshipOwnerLabel: "Responsible team", relationshipAiParticipation: "AI participation", relationshipAiEnabled: "AI enabled", relationshipProtected: "Protected", relationshipOwnerChangeConfirm: "Change the owner? Pending work may be refreshed against the new BD configuration.", relationshipHumanOnlyHint: "{{name}} is human-only, so AI will not run for this relationship." } } },
  zh: { nav: { affiliateTeam: "团队与渠道" }, ecommerce: { affiliateTeam: { ...zh, ...protectionImportCopy.zh }, affiliateWorkspace: { ...deliveryAuditCopy.zh, ...protectionWorkspaceCopy.zh, relationshipOwner: "达人关系负责人", relationshipOwnerLabel: "负责团队", relationshipAiParticipation: "AI 参与", relationshipAiEnabled: "允许 AI", relationshipProtected: "受保护", relationshipOwnerChangeConfirm: "更换负责人？待处理工作可能会根据新 BD 配置重新生成。", relationshipHumanOnlyHint: "{{name}} 设置为仅人工处理，因此该达人关系不会触发 AI。" } } },
  de: { nav: { affiliateTeam: "Team & Kanäle" }, ecommerce: { affiliateTeam: { ...de, ...protectionImportCopy.de }, affiliateWorkspace: { ...deliveryAuditCopy.de, ...protectionWorkspaceCopy.de, relationshipOwner: "Beziehungsverantwortlicher", relationshipOwnerLabel: "Zuständiges Team", relationshipAiParticipation: "KI-Beteiligung", relationshipAiEnabled: "KI aktiviert", relationshipProtected: "Geschützt", relationshipOwnerChangeConfirm: "Verantwortlichen ändern? Offene Arbeit kann aktualisiert werden.", relationshipHumanOnlyHint: "{{name}} arbeitet nur manuell; für diese Beziehung startet keine KI." } } },
  es: { nav: { affiliateTeam: "Equipo y canales" }, ecommerce: { affiliateTeam: { ...es, ...protectionImportCopy.es }, affiliateWorkspace: { ...deliveryAuditCopy.es, ...protectionWorkspaceCopy.es, relationshipOwner: "Responsable de la relación", relationshipOwnerLabel: "Equipo responsable", relationshipAiParticipation: "Participación de IA", relationshipAiEnabled: "IA activada", relationshipProtected: "Protegida", relationshipOwnerChangeConfirm: "¿Cambiar responsable? El trabajo pendiente puede actualizarse.", relationshipHumanOnlyHint: "{{name}} es solo humano; la IA no se ejecutará." } } },
  fr: { nav: { affiliateTeam: "Équipe et canaux" }, ecommerce: { affiliateTeam: { ...fr, ...protectionImportCopy.fr }, affiliateWorkspace: { ...deliveryAuditCopy.fr, ...protectionWorkspaceCopy.fr, relationshipOwner: "Responsable de la relation", relationshipOwnerLabel: "Équipe responsable", relationshipAiParticipation: "Participation de l'IA", relationshipAiEnabled: "IA activée", relationshipProtected: "Protégée", relationshipOwnerChangeConfirm: "Changer le responsable ? Le travail en attente peut être actualisé.", relationshipHumanOnlyHint: "{{name}} est en mode humain uniquement ; l'IA ne sera pas lancée." } } },
  id: { nav: { affiliateTeam: "Tim & kanal" }, ecommerce: { affiliateTeam: { ...id, ...protectionImportCopy.id }, affiliateWorkspace: { ...deliveryAuditCopy.id, ...protectionWorkspaceCopy.id, relationshipOwner: "Pemilik relasi", relationshipOwnerLabel: "Tim penanggung jawab", relationshipAiParticipation: "Partisipasi AI", relationshipAiEnabled: "AI aktif", relationshipProtected: "Dilindungi", relationshipOwnerChangeConfirm: "Ubah penanggung jawab? Pekerjaan tertunda dapat diperbarui.", relationshipHumanOnlyHint: "{{name}} hanya manusia; AI tidak akan berjalan." } } },
  it: { nav: { affiliateTeam: "Team e canali" }, ecommerce: { affiliateTeam: { ...it, ...protectionImportCopy.it }, affiliateWorkspace: { ...deliveryAuditCopy.it, ...protectionWorkspaceCopy.it, relationshipOwner: "Responsabile della relazione", relationshipOwnerLabel: "Team responsabile", relationshipAiParticipation: "Partecipazione AI", relationshipAiEnabled: "AI attiva", relationshipProtected: "Protetta", relationshipOwnerChangeConfirm: "Cambiare responsabile? Il lavoro in attesa può essere aggiornato.", relationshipHumanOnlyHint: "{{name}} è solo umano; l'AI non verrà eseguita." } } },
  th: { nav: { affiliateTeam: "ทีมและช่องทาง" }, ecommerce: { affiliateTeam: { ...th, ...protectionImportCopy.th }, affiliateWorkspace: { ...deliveryAuditCopy.th, ...protectionWorkspaceCopy.th, relationshipOwner: "ผู้รับผิดชอบความสัมพันธ์", relationshipOwnerLabel: "ทีมที่รับผิดชอบ", relationshipAiParticipation: "การใช้ AI", relationshipAiEnabled: "เปิด AI", relationshipProtected: "ปกป้อง", relationshipOwnerChangeConfirm: "เปลี่ยนผู้รับผิดชอบหรือไม่ งานที่ค้างอาจถูกรีเฟรช", relationshipHumanOnlyHint: "{{name}} ตั้งเป็นคนดูแลเท่านั้น จึงไม่เรียกใช้ AI" } } },
} as const;
