const operationalCopy = {
  en: {
    operationsOverview: "Affiliate operations overview", setupStatus: "Setup status", setupReady: "Ready for operations", setupRequired: "Review the AI boundary", humanDevelopers: "Human BDs", connectedChannels: "Outreach accounts", unassignedChannels: "{{count}} assigned to the AI team", protectedCreators: "Protected creators", appliedProtections: "{{count}} matched to relationships",
    protectionBoundary: "AI operating boundary", protectionBoundaryReady: "The boundary is active. Add protected creators whenever your human team takes ownership of another relationship.", showProtectionManager: "Add protected creators", hideProtectionManager: "Close", addProtectionEntries: "Add protection entries", protectionEntryHint: "Use a creator username or platform Open ID, then optionally assign the responsible BD.", assignProtectionDeveloper: "Human BD (optional)", protectionUnassigned: "No human BD (protection only)", removePreviewRow: "Remove row", templateField: "Field", templateRequirement: "Requirement", templateInstructions: "How to fill it", templateRequired: "Required", templateOptional: "Optional", templateIdentityRequired: "Provide one", templateIdentityHint: "Enter either the platform creator Open ID or username.", templateDeveloperHint: "Enter the BD's exact display name from Team & channels. Leave blank for protection only. Do not enter a system ID.", templateNoteHint: "Optional reason or migration note.",
    responsibilityMap: "Responsibility map", responsibilityTitle: "Owners and outreach accounts", responsibilityHint: "Select an owner to review its working mode, instructions, and assigned contact accounts.", ownerCount: "{{count}} owners",
  },
  zh: {
    operationsOverview: "Affiliate 运营概览", setupStatus: "设置状态", setupReady: "已可投入运营", setupRequired: "待确认 AI 边界", humanDevelopers: "人工 BD", connectedChannels: "联络账号", unassignedChannels: "{{count}} 个归属 AI 团队", protectedCreators: "受保护达人", appliedProtections: "{{count}} 个已匹配达人关系",
    protectionBoundary: "AI 工作边界", protectionBoundaryReady: "保护边界已生效。人工团队接手新的达人关系时，仍可随时追加受保护达人。", showProtectionManager: "添加受保护达人", hideProtectionManager: "收起", addProtectionEntries: "添加保护记录", protectionEntryHint: "填写达人用户名或平台 Open ID，并可选择负责这段关系的 BD。", assignProtectionDeveloper: "负责人工 BD（可选）", protectionUnassigned: "暂不指定人工 BD（仅保护）", removePreviewRow: "移除这条记录", templateField: "字段", templateRequirement: "是否必填", templateInstructions: "填写说明", templateRequired: "必填", templateOptional: "可选", templateIdentityRequired: "二选一", templateIdentityHint: "填写平台达人 Open ID 或用户名中的任意一个。", templateDeveloperHint: "填写“团队与渠道”页面中的 BD 完整显示名称；仅保护时留空。请勿填写系统 ID。", templateNoteHint: "可填写保护原因或迁移备注。",
    responsibilityMap: "责任分配", responsibilityTitle: "负责人和联络账号", responsibilityHint: "选择负责人，查看其工作模式、业务指引和名下联络账号。", ownerCount: "{{count}} 个负责人",
  },
  de: {
    operationsOverview: "Übersicht Affiliate-Betrieb", setupStatus: "Einrichtungsstatus", setupReady: "Betriebsbereit", setupRequired: "KI-Grenze prüfen", humanDevelopers: "Menschliche BDs", connectedChannels: "Kontaktkonten", unassignedChannels: "{{count}} beim KI-Team", protectedCreators: "Geschützte Creator", appliedProtections: "{{count}} Beziehungen zugeordnet",
    protectionBoundary: "KI-Arbeitsgrenze", protectionBoundaryReady: "Die Grenze ist aktiv. Weitere vom Team übernommene Creator können jederzeit geschützt werden.", showProtectionManager: "Creator schützen", hideProtectionManager: "Schließen", addProtectionEntries: "Schutzeinträge hinzufügen", protectionEntryHint: "Username oder Open ID angeben und optional den zuständigen BD auswählen.", assignProtectionDeveloper: "Menschlicher BD (optional)", protectionUnassigned: "Kein menschlicher BD (nur schützen)", removePreviewRow: "Zeile entfernen", templateField: "Feld", templateRequirement: "Anforderung", templateInstructions: "Ausfüllhinweis", templateRequired: "Erforderlich", templateOptional: "Optional", templateIdentityRequired: "Eines angeben", templateIdentityHint: "Creator Open ID oder Username der Plattform eingeben.", templateDeveloperHint: "Exakten Anzeigenamen des BD aus Team & Kanäle eingeben. Für reinen Schutz leer lassen. Keine System-ID eingeben.", templateNoteHint: "Optionaler Schutzgrund oder Migrationshinweis.",
    responsibilityMap: "Verantwortungsmatrix", responsibilityTitle: "Verantwortliche und Kontaktkonten", responsibilityHint: "Verantwortlichen auswählen, um Arbeitsmodus, Hinweise und Konten zu prüfen.", ownerCount: "{{count}} Verantwortliche",
  },
  es: {
    operationsOverview: "Resumen de operaciones", setupStatus: "Estado de configuración", setupReady: "Listo para operar", setupRequired: "Revisar el límite de IA", humanDevelopers: "BD humanos", connectedChannels: "Cuentas de contacto", unassignedChannels: "{{count}} en el equipo de IA", protectedCreators: "Creadores protegidos", appliedProtections: "{{count}} relaciones vinculadas",
    protectionBoundary: "Límite operativo de IA", protectionBoundaryReady: "El límite está activo. Añade creadores protegidos cuando el equipo humano asuma otra relación.", showProtectionManager: "Añadir protegidos", hideProtectionManager: "Cerrar", addProtectionEntries: "Añadir protecciones", protectionEntryHint: "Indica usuario u Open ID y, si procede, el BD responsable.", assignProtectionDeveloper: "BD humano (opcional)", protectionUnassigned: "Sin BD humano (solo proteger)", removePreviewRow: "Eliminar fila", templateField: "Campo", templateRequirement: "Requisito", templateInstructions: "Cómo completarlo", templateRequired: "Obligatorio", templateOptional: "Opcional", templateIdentityRequired: "Indica uno", templateIdentityHint: "Introduce el Open ID o el usuario del creador.", templateDeveloperHint: "Introduce el nombre visible exacto del BD en Equipo y canales. Déjalo vacío para solo proteger. No uses un ID del sistema.", templateNoteHint: "Motivo de protección o nota de migración opcional.",
    responsibilityMap: "Mapa de responsabilidad", responsibilityTitle: "Responsables y cuentas de contacto", responsibilityHint: "Selecciona un responsable para revisar su modo, instrucciones y cuentas.", ownerCount: "{{count}} responsables",
  },
  fr: {
    operationsOverview: "Vue des opérations", setupStatus: "État de configuration", setupReady: "Prêt à fonctionner", setupRequired: "Vérifier la limite IA", humanDevelopers: "BD humains", connectedChannels: "Comptes de contact", unassignedChannels: "{{count}} dans l'équipe IA", protectedCreators: "Créateurs protégés", appliedProtections: "{{count}} relations associées",
    protectionBoundary: "Limite d'action de l'IA", protectionBoundaryReady: "La limite est active. Ajoutez des créateurs protégés lorsque l'équipe humaine reprend une relation.", showProtectionManager: "Ajouter des protégés", hideProtectionManager: "Fermer", addProtectionEntries: "Ajouter des protections", protectionEntryHint: "Indiquez l'identifiant ou l'Open ID, puis éventuellement le BD responsable.", assignProtectionDeveloper: "BD humain (facultatif)", protectionUnassigned: "Aucun BD humain (protection seule)", removePreviewRow: "Supprimer la ligne", templateField: "Champ", templateRequirement: "Exigence", templateInstructions: "Comment le remplir", templateRequired: "Obligatoire", templateOptional: "Facultatif", templateIdentityRequired: "Un des deux", templateIdentityHint: "Saisissez l'Open ID ou le nom d'utilisateur du créateur.", templateDeveloperHint: "Saisissez le nom d'affichage exact du BD dans Équipe et canaux. Laissez vide pour protéger uniquement. N'utilisez pas d'ID système.", templateNoteHint: "Motif de protection ou note de migration facultative.",
    responsibilityMap: "Répartition des responsabilités", responsibilityTitle: "Responsables et comptes de contact", responsibilityHint: "Sélectionnez un responsable pour consulter son mode, ses consignes et ses comptes.", ownerCount: "{{count}} responsables",
  },
  id: {
    operationsOverview: "Ringkasan operasi afiliasi", setupStatus: "Status penyiapan", setupReady: "Siap beroperasi", setupRequired: "Tinjau batas AI", humanDevelopers: "BD manusia", connectedChannels: "Akun kontak", unassignedChannels: "{{count}} milik tim AI", protectedCreators: "Kreator terlindungi", appliedProtections: "{{count}} relasi cocok",
    protectionBoundary: "Batas kerja AI", protectionBoundaryReady: "Batas sudah aktif. Tambahkan kreator terlindungi saat tim manusia mengambil relasi baru.", showProtectionManager: "Tambah kreator terlindungi", hideProtectionManager: "Tutup", addProtectionEntries: "Tambah perlindungan", protectionEntryHint: "Masukkan username atau Open ID dan pilih BD bila diperlukan.", assignProtectionDeveloper: "BD manusia (opsional)", protectionUnassigned: "Tanpa BD manusia (hanya dilindungi)", removePreviewRow: "Hapus baris", templateField: "Kolom", templateRequirement: "Ketentuan", templateInstructions: "Cara mengisi", templateRequired: "Wajib", templateOptional: "Opsional", templateIdentityRequired: "Isi salah satu", templateIdentityHint: "Masukkan Open ID kreator atau username platform.", templateDeveloperHint: "Masukkan nama tampilan BD persis seperti di Tim & kanal. Kosongkan untuk hanya melindungi. Jangan masukkan ID sistem.", templateNoteHint: "Alasan perlindungan atau catatan migrasi opsional.",
    responsibilityMap: "Peta tanggung jawab", responsibilityTitle: "Penanggung jawab dan akun kontak", responsibilityHint: "Pilih penanggung jawab untuk melihat mode kerja, instruksi, dan akun.", ownerCount: "{{count}} penanggung jawab",
  },
  it: {
    operationsOverview: "Panoramica operativa", setupStatus: "Stato configurazione", setupReady: "Pronto per operare", setupRequired: "Verifica il confine AI", humanDevelopers: "BD umani", connectedChannels: "Account di contatto", unassignedChannels: "{{count}} al team AI", protectedCreators: "Creator protetti", appliedProtections: "{{count}} relazioni associate",
    protectionBoundary: "Confine operativo AI", protectionBoundaryReady: "Il confine è attivo. Aggiungi creator protetti quando il team umano prende in carico nuove relazioni.", showProtectionManager: "Aggiungi protetti", hideProtectionManager: "Chiudi", addProtectionEntries: "Aggiungi protezioni", protectionEntryHint: "Inserisci username o Open ID e, se necessario, assegna il BD.", assignProtectionDeveloper: "BD umano (facoltativo)", protectionUnassigned: "Nessun BD umano (solo protezione)", removePreviewRow: "Rimuovi riga", templateField: "Campo", templateRequirement: "Requisito", templateInstructions: "Come compilarlo", templateRequired: "Obbligatorio", templateOptional: "Facoltativo", templateIdentityRequired: "Inserirne uno", templateIdentityHint: "Inserisci l'Open ID o lo username del creator.", templateDeveloperHint: "Inserisci il nome visualizzato esatto del BD in Team e canali. Lascia vuoto per la sola protezione. Non inserire un ID di sistema.", templateNoteHint: "Motivo della protezione o nota di migrazione facoltativa.",
    responsibilityMap: "Mappa delle responsabilità", responsibilityTitle: "Responsabili e account di contatto", responsibilityHint: "Seleziona un responsabile per vedere modalità, istruzioni e account.", ownerCount: "{{count}} responsabili",
  },
  th: {
    operationsOverview: "ภาพรวมงาน Affiliate", setupStatus: "สถานะการตั้งค่า", setupReady: "พร้อมใช้งาน", setupRequired: "ตรวจสอบขอบเขต AI", humanDevelopers: "BD ที่เป็นคน", connectedChannels: "บัญชีติดต่อ", unassignedChannels: "{{count}} บัญชีอยู่กับทีม AI", protectedCreators: "ครีเอเตอร์ที่ปกป้อง", appliedProtections: "จับคู่แล้ว {{count}} ความสัมพันธ์",
    protectionBoundary: "ขอบเขตการทำงานของ AI", protectionBoundaryReady: "ขอบเขตมีผลแล้ว เพิ่มครีเอเตอร์ที่ปกป้องได้เมื่อทีมคนรับดูแลความสัมพันธ์ใหม่", showProtectionManager: "เพิ่มครีเอเตอร์ที่ปกป้อง", hideProtectionManager: "ปิด", addProtectionEntries: "เพิ่มรายการปกป้อง", protectionEntryHint: "กรอก username หรือ Open ID และเลือก BD ผู้รับผิดชอบได้", assignProtectionDeveloper: "BD ที่เป็นคน (ไม่บังคับ)", protectionUnassigned: "ไม่ระบุ BD ที่เป็นคน (ปกป้องเท่านั้น)", removePreviewRow: "ลบแถว", templateField: "ฟิลด์", templateRequirement: "ข้อกำหนด", templateInstructions: "วิธีกรอก", templateRequired: "จำเป็น", templateOptional: "ไม่บังคับ", templateIdentityRequired: "กรอกอย่างใดอย่างหนึ่ง", templateIdentityHint: "กรอก Open ID หรือ username ของครีเอเตอร์บนแพลตฟอร์ม", templateDeveloperHint: "กรอกชื่อที่แสดงของ BD ให้ตรงกับหน้า ทีมและช่องทาง เว้นว่างเมื่อต้องการปกป้องเท่านั้น ห้ามกรอก System ID", templateNoteHint: "เหตุผลในการปกป้องหรือบันทึกการย้ายข้อมูล (ไม่บังคับ)",
    responsibilityMap: "แผนผังผู้รับผิดชอบ", responsibilityTitle: "ผู้รับผิดชอบและบัญชีติดต่อ", responsibilityHint: "เลือกผู้รับผิดชอบเพื่อดูโหมด คำแนะนำ และบัญชีที่ได้รับมอบหมาย", ownerCount: "ผู้รับผิดชอบ {{count}} ราย",
  },
} as const;

const en = {
  eyebrow: "Affiliate operations", title: "Team & channels", subtitle: "Assign creator relationships and outreach accounts to the people responsible for moving them forward.",
  addDeveloper: "Add BD", aiTeam: "AI team", aiTeamHint: "Unassigned relationships", aiTeamDescription: "The AI team handles eligible creator relationships that are not assigned to a human BD.",
  businessDeveloper: "Business developer", virtualOwner: "Default owner", developerHint: "This BD's working mode and instructions apply to every assigned creator relationship.",
  roster: "Owners", workMode: "Work mode", aiAssisted: "AI assisted", humanOnly: "Human only", aiManaged: "AI managed", acceptingCreators: "Accepting new creators",
  whatsappAccounts: "WhatsApp accounts", emailAccounts: "Email accounts", channels: "Channels", connectChannel: "Connect channel", noChannels: "No outreach accounts are assigned to this owner.", unnamedAccount: "Unnamed account",
  workingStyle: "Working style", workingStylePlaceholder: "Describe this BD's tone, priorities, negotiation habits, and handoff preferences.", regions: "Regions", name: "Name", newDeveloper: "New business developer", nameRequired: "Enter a BD name.", saved: "BD settings saved.",
  archive: "Archive", archiveConfirm: "Archive {{name}}? Reassign their creators and accounts first.", archived: "BD archived.", transferConfirm: "Move this account? Related creator channels will be rebound and pending work may be refreshed.", accountMoved: "Account owner updated.",
  onboardingStep: "Affiliate setup", onboardingTitle: "Protect existing BD relationships before AI starts", onboardingHint: "Import creators your current team already manages. Unlisted, unassigned relationships become eligible for the AI team after confirmation.",
  downloadTemplate: "Download template", importProtected: "Import protected creators", importPreview: "Import preview", importValid: "Import {{count}} valid rows", protectedOnly: "Protected only", ready: "Ready",
  creatorIdentity: "Creator identity", creatorIdentityPlaceholder: "@username or creator open ID", assignDeveloper: "Responsible BD", note: "Note", notePlaceholder: "Why this relationship is protected", addProtectedCreator: "Add protected creator",
  emptySpreadsheet: "The spreadsheet has no readable worksheet.", missingCreatorIdentity: "Provide creator_open_id or username.", duplicateCreator: "Duplicate creator in this file.", unknownDeveloper: "BD “{{name}}” does not exist.", protectionsImported: "Imported {{count}} protected creators.",
  confirmBoundary: "I reviewed the protected creator list. Relationships that are not protected and not assigned to a human BD may be handled by the AI team.", completeSetup: "Complete setup and enable AI", onboardingCompleted: "Affiliate operational setup completed.",
  ...operationalCopy.en,
} as const;

const zh = {
  eyebrow: "Affiliate 运营", title: "团队与渠道", subtitle: "把达人关系和联络渠道分配给真正负责推进合作的人。",
  addDeveloper: "新增 BD", aiTeam: "AI 团队", aiTeamHint: "未分配的达人关系", aiTeamDescription: "AI 团队负责所有未分配给人工 BD 且允许 AI 参与的达人关系。",
  businessDeveloper: "商务开发", virtualOwner: "默认负责人", developerHint: "该 BD 的工作模式和业务习惯会作用于名下所有达人关系。",
  roster: "负责人", workMode: "工作模式", aiAssisted: "AI 辅助", humanOnly: "仅人工处理", aiManaged: "AI 管理", acceptingCreators: "接收新达人",
  whatsappAccounts: "WhatsApp 账号", emailAccounts: "邮箱账号", channels: "联络渠道", connectChannel: "连接渠道", noChannels: "该负责人尚未分配任何联络账号。", unnamedAccount: "未命名账号",
  workingStyle: "工作习惯", workingStylePlaceholder: "描述该 BD 的沟通语气、业务重点、议价习惯和交接偏好。", regions: "负责地区", name: "姓名", newDeveloper: "新增商务开发", nameRequired: "请输入 BD 姓名。", saved: "BD 设置已保存。",
  archive: "归档", archiveConfirm: "归档 {{name}}？请先转移其达人关系和账号。", archived: "BD 已归档。", transferConfirm: "转移这个账号？相关达人渠道会重新归属，待处理工作也可能刷新。", accountMoved: "账号负责人已更新。",
  onboardingStep: "Affiliate 初始化", onboardingTitle: "在 AI 开始工作前保护现有 BD 关系", onboardingHint: "导入目前由人工团队维护的达人。确认后，未被保护且未分配人工 BD 的关系将由 AI 团队处理。",
  downloadTemplate: "下载模板", importProtected: "导入受保护达人", importPreview: "导入预览", importValid: "导入 {{count}} 条有效记录", protectedOnly: "仅保护", ready: "可导入",
  creatorIdentity: "达人身份", creatorIdentityPlaceholder: "@用户名或达人 Open ID", assignDeveloper: "负责 BD", note: "备注", notePlaceholder: "说明保护这段关系的原因", addProtectedCreator: "添加受保护达人",
  emptySpreadsheet: "表格中没有可读取的工作表。", missingCreatorIdentity: "请填写 creator_open_id 或 username。", duplicateCreator: "文件中达人重复。", unknownDeveloper: "BD“{{name}}”不存在。", protectionsImported: "已导入 {{count}} 个受保护达人。",
  confirmBoundary: "我已检查受保护达人名单；未被保护且未分配人工 BD 的达人关系可以由 AI 团队处理。", completeSetup: "完成设置并启用 AI", onboardingCompleted: "Affiliate 运营设置已完成。",
  ...operationalCopy.zh,
} as const;

const de = {
  eyebrow: "Affiliate-Betrieb", title: "Team & Kanäle", subtitle: "Creator-Beziehungen und Kontaktkonten den zuständigen Personen zuweisen.", addDeveloper: "BD hinzufügen", aiTeam: "KI-Team", aiTeamHint: "Nicht zugewiesene Beziehungen", aiTeamDescription: "Das KI-Team bearbeitet geeignete Beziehungen ohne menschlichen BD.", businessDeveloper: "Business Developer", virtualOwner: "Standardverantwortlicher", developerHint: "Arbeitsmodus und Anweisungen gelten für alle zugewiesenen Creator.", roster: "Verantwortliche", workMode: "Arbeitsmodus", aiAssisted: "KI-unterstützt", humanOnly: "Nur manuell", aiManaged: "KI-verwaltet", acceptingCreators: "Nimmt neue Creator an", whatsappAccounts: "WhatsApp-Konten", emailAccounts: "E-Mail-Konten", channels: "Kanäle", connectChannel: "Kanal verbinden", noChannels: "Keine Kontaktkonten zugewiesen.", unnamedAccount: "Unbenanntes Konto", workingStyle: "Arbeitsweise", workingStylePlaceholder: "Ton, Prioritäten, Verhandlungs- und Übergabegewohnheiten beschreiben.", regions: "Regionen", name: "Name", newDeveloper: "Neuer Business Developer", nameRequired: "BD-Namen eingeben.", saved: "BD-Einstellungen gespeichert.", archive: "Archivieren", archiveConfirm: "{{name}} archivieren? Creator und Konten zuerst neu zuweisen.", archived: "BD archiviert.", transferConfirm: "Konto verschieben? Zugehörige Kanäle und offene Arbeit werden aktualisiert.", accountMoved: "Kontoinhaber aktualisiert.", onboardingStep: "Affiliate-Einrichtung", onboardingTitle: "Bestehende BD-Beziehungen vor dem KI-Start schützen", onboardingHint: "Bereits betreute Creator importieren. Andere nicht zugewiesene Beziehungen werden nach Bestätigung KI-fähig.", downloadTemplate: "Vorlage laden", importProtected: "Geschützte Creator importieren", importPreview: "Importvorschau", importValid: "{{count}} gültige Zeilen importieren", protectedOnly: "Nur geschützt", ready: "Bereit", creatorIdentity: "Creator-Identität", creatorIdentityPlaceholder: "@Username oder Open ID", assignDeveloper: "Zuständiger BD", note: "Notiz", notePlaceholder: "Grund für den Schutz", addProtectedCreator: "Creator schützen", emptySpreadsheet: "Keine lesbare Tabelle gefunden.", missingCreatorIdentity: "creator_open_id oder username angeben.", duplicateCreator: "Creator ist doppelt vorhanden.", unknownDeveloper: "BD „{{name}}“ existiert nicht.", protectionsImported: "{{count}} geschützte Creator importiert.", confirmBoundary: "Ich habe die Schutzliste geprüft. Nicht geschützte, nicht zugewiesene Beziehungen darf das KI-Team bearbeiten.", completeSetup: "Einrichtung abschließen und KI aktivieren", onboardingCompleted: "Affiliate-Einrichtung abgeschlossen.", ...operationalCopy.de,
} as const;

const es = {
  eyebrow: "Operaciones de afiliados", title: "Equipo y canales", subtitle: "Asigna relaciones y cuentas de contacto a las personas responsables.", addDeveloper: "Añadir BD", aiTeam: "Equipo de IA", aiTeamHint: "Relaciones sin asignar", aiTeamDescription: "El equipo de IA gestiona relaciones aptas sin un BD humano.", businessDeveloper: "Desarrollo de negocio", virtualOwner: "Responsable predeterminado", developerHint: "El modo y las instrucciones del BD se aplican a sus creadores.", roster: "Responsables", workMode: "Modo de trabajo", aiAssisted: "Asistido por IA", humanOnly: "Solo humano", aiManaged: "Gestionado por IA", acceptingCreators: "Acepta nuevos creadores", whatsappAccounts: "Cuentas de WhatsApp", emailAccounts: "Cuentas de correo", channels: "Canales", connectChannel: "Conectar canal", noChannels: "No hay cuentas asignadas.", unnamedAccount: "Cuenta sin nombre", workingStyle: "Estilo de trabajo", workingStylePlaceholder: "Describe tono, prioridades, negociación y traspasos.", regions: "Regiones", name: "Nombre", newDeveloper: "Nuevo BD", nameRequired: "Introduce el nombre del BD.", saved: "Configuración guardada.", archive: "Archivar", archiveConfirm: "¿Archivar a {{name}}? Reasigna antes sus creadores y cuentas.", archived: "BD archivado.", transferConfirm: "¿Mover esta cuenta? Se reasignarán canales y trabajos pendientes.", accountMoved: "Responsable actualizado.", onboardingStep: "Configuración de afiliados", onboardingTitle: "Protege relaciones existentes antes de activar la IA", onboardingHint: "Importa creadores ya gestionados. Los demás podrán pasar al equipo de IA.", downloadTemplate: "Descargar plantilla", importProtected: "Importar protegidos", importPreview: "Vista previa", importValid: "Importar {{count}} filas válidas", protectedOnly: "Solo protegido", ready: "Listo", creatorIdentity: "Identidad del creador", creatorIdentityPlaceholder: "@usuario u Open ID", assignDeveloper: "BD responsable", note: "Nota", notePlaceholder: "Motivo de protección", addProtectedCreator: "Proteger creador", emptySpreadsheet: "La hoja no contiene datos legibles.", missingCreatorIdentity: "Indica creator_open_id o username.", duplicateCreator: "Creador duplicado.", unknownDeveloper: "El BD «{{name}}» no existe.", protectionsImported: "Se importaron {{count}} creadores protegidos.", confirmBoundary: "He revisado la lista. El equipo de IA puede gestionar relaciones no protegidas y sin BD humano.", completeSetup: "Completar y activar IA", onboardingCompleted: "Configuración completada.", ...operationalCopy.es,
} as const;

const fr = {
  eyebrow: "Opérations d'affiliation", title: "Équipe et canaux", subtitle: "Attribuez les relations et comptes de contact aux responsables.", addDeveloper: "Ajouter un BD", aiTeam: "Équipe IA", aiTeamHint: "Relations non attribuées", aiTeamDescription: "L'équipe IA gère les relations éligibles sans BD humain.", businessDeveloper: "Business developer", virtualOwner: "Responsable par défaut", developerHint: "Le mode et les consignes du BD s'appliquent à ses créateurs.", roster: "Responsables", workMode: "Mode de travail", aiAssisted: "Assisté par IA", humanOnly: "Humain uniquement", aiManaged: "Géré par IA", acceptingCreators: "Accepte de nouveaux créateurs", whatsappAccounts: "Comptes WhatsApp", emailAccounts: "Comptes e-mail", channels: "Canaux", connectChannel: "Connecter un canal", noChannels: "Aucun compte attribué.", unnamedAccount: "Compte sans nom", workingStyle: "Méthode de travail", workingStylePlaceholder: "Décrivez ton, priorités, négociation et transmission.", regions: "Régions", name: "Nom", newDeveloper: "Nouveau BD", nameRequired: "Saisissez le nom du BD.", saved: "Paramètres enregistrés.", archive: "Archiver", archiveConfirm: "Archiver {{name}} ? Réattribuez d'abord ses créateurs et comptes.", archived: "BD archivé.", transferConfirm: "Déplacer ce compte ? Les canaux et travaux associés seront actualisés.", accountMoved: "Responsable du compte mis à jour.", onboardingStep: "Configuration Affiliate", onboardingTitle: "Protégez les relations existantes avant l'IA", onboardingHint: "Importez les créateurs déjà suivis. Les autres pourront être gérés par l'équipe IA.", downloadTemplate: "Télécharger le modèle", importProtected: "Importer les créateurs protégés", importPreview: "Aperçu", importValid: "Importer {{count}} lignes valides", protectedOnly: "Protection seule", ready: "Prêt", creatorIdentity: "Identité du créateur", creatorIdentityPlaceholder: "@identifiant ou Open ID", assignDeveloper: "BD responsable", note: "Note", notePlaceholder: "Motif de protection", addProtectedCreator: "Protéger le créateur", emptySpreadsheet: "Aucune feuille lisible.", missingCreatorIdentity: "Indiquez creator_open_id ou username.", duplicateCreator: "Créateur en double.", unknownDeveloper: "Le BD « {{name}} » n'existe pas.", protectionsImported: "{{count}} créateurs protégés importés.", confirmBoundary: "J'ai vérifié la liste. L'équipe IA peut gérer les relations non protégées et sans BD humain.", completeSetup: "Terminer et activer l'IA", onboardingCompleted: "Configuration terminée.", ...operationalCopy.fr,
} as const;

const id = {
  eyebrow: "Operasi afiliasi", title: "Tim & kanal", subtitle: "Tetapkan relasi kreator dan akun kontak kepada penanggung jawab.", addDeveloper: "Tambah BD", aiTeam: "Tim AI", aiTeamHint: "Relasi belum ditugaskan", aiTeamDescription: "Tim AI menangani relasi yang memenuhi syarat tanpa BD manusia.", businessDeveloper: "Business developer", virtualOwner: "Pemilik default", developerHint: "Mode dan instruksi BD berlaku untuk semua kreator yang ditugaskan.", roster: "Penanggung jawab", workMode: "Mode kerja", aiAssisted: "Dibantu AI", humanOnly: "Hanya manusia", aiManaged: "Dikelola AI", acceptingCreators: "Menerima kreator baru", whatsappAccounts: "Akun WhatsApp", emailAccounts: "Akun email", channels: "Kanal", connectChannel: "Hubungkan kanal", noChannels: "Belum ada akun yang ditugaskan.", unnamedAccount: "Akun tanpa nama", workingStyle: "Gaya kerja", workingStylePlaceholder: "Jelaskan nada, prioritas, negosiasi, dan serah terima.", regions: "Wilayah", name: "Nama", newDeveloper: "BD baru", nameRequired: "Masukkan nama BD.", saved: "Pengaturan tersimpan.", archive: "Arsipkan", archiveConfirm: "Arsipkan {{name}}? Pindahkan kreator dan akunnya dahulu.", archived: "BD diarsipkan.", transferConfirm: "Pindahkan akun ini? Kanal dan pekerjaan terkait akan diperbarui.", accountMoved: "Pemilik akun diperbarui.", onboardingStep: "Penyiapan afiliasi", onboardingTitle: "Lindungi relasi BD sebelum AI dimulai", onboardingHint: "Impor kreator yang sudah dikelola. Relasi lain dapat ditangani tim AI.", downloadTemplate: "Unduh templat", importProtected: "Impor kreator terlindungi", importPreview: "Pratinjau impor", importValid: "Impor {{count}} baris valid", protectedOnly: "Hanya dilindungi", ready: "Siap", creatorIdentity: "Identitas kreator", creatorIdentityPlaceholder: "@username atau Open ID", assignDeveloper: "BD penanggung jawab", note: "Catatan", notePlaceholder: "Alasan perlindungan", addProtectedCreator: "Lindungi kreator", emptySpreadsheet: "Tidak ada lembar yang dapat dibaca.", missingCreatorIdentity: "Isi creator_open_id atau username.", duplicateCreator: "Kreator duplikat.", unknownDeveloper: "BD “{{name}}” tidak ada.", protectionsImported: "{{count}} kreator terlindungi diimpor.", confirmBoundary: "Saya telah meninjau daftar. Tim AI boleh menangani relasi yang tidak dilindungi dan tanpa BD manusia.", completeSetup: "Selesaikan dan aktifkan AI", onboardingCompleted: "Penyiapan selesai.", ...operationalCopy.id,
} as const;

const it = {
  eyebrow: "Operazioni affiliate", title: "Team e canali", subtitle: "Assegna relazioni e account di contatto ai responsabili.", addDeveloper: "Aggiungi BD", aiTeam: "Team AI", aiTeamHint: "Relazioni non assegnate", aiTeamDescription: "Il team AI gestisce le relazioni idonee senza BD umano.", businessDeveloper: "Business developer", virtualOwner: "Responsabile predefinito", developerHint: "Modalità e istruzioni del BD si applicano ai creator assegnati.", roster: "Responsabili", workMode: "Modalità di lavoro", aiAssisted: "Assistito da AI", humanOnly: "Solo umano", aiManaged: "Gestito da AI", acceptingCreators: "Accetta nuovi creator", whatsappAccounts: "Account WhatsApp", emailAccounts: "Account email", channels: "Canali", connectChannel: "Collega canale", noChannels: "Nessun account assegnato.", unnamedAccount: "Account senza nome", workingStyle: "Stile di lavoro", workingStylePlaceholder: "Descrivi tono, priorità, negoziazione e passaggi di consegna.", regions: "Regioni", name: "Nome", newDeveloper: "Nuovo BD", nameRequired: "Inserisci il nome del BD.", saved: "Impostazioni salvate.", archive: "Archivia", archiveConfirm: "Archiviare {{name}}? Riassegna prima creator e account.", archived: "BD archiviato.", transferConfirm: "Spostare questo account? Canali e lavori collegati verranno aggiornati.", accountMoved: "Responsabile aggiornato.", onboardingStep: "Configurazione affiliate", onboardingTitle: "Proteggi le relazioni esistenti prima dell'AI", onboardingHint: "Importa i creator già gestiti. Gli altri potranno essere gestiti dal team AI.", downloadTemplate: "Scarica modello", importProtected: "Importa creator protetti", importPreview: "Anteprima", importValid: "Importa {{count}} righe valide", protectedOnly: "Solo protetto", ready: "Pronto", creatorIdentity: "Identità creator", creatorIdentityPlaceholder: "@username o Open ID", assignDeveloper: "BD responsabile", note: "Nota", notePlaceholder: "Motivo della protezione", addProtectedCreator: "Proteggi creator", emptySpreadsheet: "Nessun foglio leggibile.", missingCreatorIdentity: "Inserisci creator_open_id o username.", duplicateCreator: "Creator duplicato.", unknownDeveloper: "Il BD “{{name}}” non esiste.", protectionsImported: "Importati {{count}} creator protetti.", confirmBoundary: "Ho verificato l'elenco. Il team AI può gestire relazioni non protette e senza BD umano.", completeSetup: "Completa e attiva AI", onboardingCompleted: "Configurazione completata.", ...operationalCopy.it,
} as const;

const th = {
  eyebrow: "งาน Affiliate", title: "ทีมและช่องทาง", subtitle: "มอบหมายความสัมพันธ์และบัญชีติดต่อให้ผู้รับผิดชอบ", addDeveloper: "เพิ่ม BD", aiTeam: "ทีม AI", aiTeamHint: "ความสัมพันธ์ที่ยังไม่มอบหมาย", aiTeamDescription: "ทีม AI ดูแลความสัมพันธ์ที่เข้าเกณฑ์และไม่มี BD", businessDeveloper: "Business developer", virtualOwner: "ผู้รับผิดชอบเริ่มต้น", developerHint: "โหมดและคำแนะนำของ BD ใช้กับครีเอเตอร์ที่ได้รับมอบหมาย", roster: "ผู้รับผิดชอบ", workMode: "โหมดการทำงาน", aiAssisted: "AI ช่วยงาน", humanOnly: "คนดูแลเท่านั้น", aiManaged: "AI ดูแล", acceptingCreators: "รับครีเอเตอร์ใหม่", whatsappAccounts: "บัญชี WhatsApp", emailAccounts: "บัญชีอีเมล", channels: "ช่องทาง", connectChannel: "เชื่อมต่อช่องทาง", noChannels: "ยังไม่มีบัญชีที่มอบหมาย", unnamedAccount: "บัญชีไม่มีชื่อ", workingStyle: "รูปแบบการทำงาน", workingStylePlaceholder: "ระบุน้ำเสียง ลำดับความสำคัญ การเจรจา และการส่งต่องาน", regions: "ภูมิภาค", name: "ชื่อ", newDeveloper: "BD ใหม่", nameRequired: "กรุณาใส่ชื่อ BD", saved: "บันทึกแล้ว", archive: "เก็บถาวร", archiveConfirm: "เก็บ {{name}} หรือไม่ โปรดย้ายครีเอเตอร์และบัญชีก่อน", archived: "เก็บ BD แล้ว", transferConfirm: "ย้ายบัญชีนี้หรือไม่ ช่องทางและงานที่เกี่ยวข้องจะถูกรีเฟรช", accountMoved: "อัปเดตผู้รับผิดชอบแล้ว", onboardingStep: "ตั้งค่า Affiliate", onboardingTitle: "ปกป้องความสัมพันธ์เดิมก่อนเปิด AI", onboardingHint: "นำเข้าครีเอเตอร์ที่ทีมดูแลอยู่ ความสัมพันธ์อื่นสามารถให้ทีม AI ดูแลได้", downloadTemplate: "ดาวน์โหลดแม่แบบ", importProtected: "นำเข้าครีเอเตอร์ที่ปกป้อง", importPreview: "ตัวอย่างนำเข้า", importValid: "นำเข้า {{count}} แถว", protectedOnly: "ปกป้องเท่านั้น", ready: "พร้อม", creatorIdentity: "ตัวตนครีเอเตอร์", creatorIdentityPlaceholder: "@username หรือ Open ID", assignDeveloper: "BD ผู้รับผิดชอบ", note: "หมายเหตุ", notePlaceholder: "เหตุผลที่ปกป้อง", addProtectedCreator: "เพิ่มครีเอเตอร์", emptySpreadsheet: "ไม่พบชีตที่อ่านได้", missingCreatorIdentity: "กรอก creator_open_id หรือ username", duplicateCreator: "ครีเอเตอร์ซ้ำ", unknownDeveloper: "ไม่พบ BD “{{name}}”", protectionsImported: "นำเข้า {{count}} ครีเอเตอร์แล้ว", confirmBoundary: "ฉันตรวจสอบรายชื่อแล้ว ทีม AI สามารถดูแลความสัมพันธ์ที่ไม่ถูกปกป้องและไม่มี BD ได้", completeSetup: "เสร็จสิ้นและเปิด AI", onboardingCompleted: "ตั้งค่าเสร็จแล้ว", ...operationalCopy.th,
} as const;

export const AFFILIATE_TEAM_TRANSLATIONS = {
  en: { nav: { affiliateTeam: "Team & channels" }, ecommerce: { affiliateTeam: en, affiliateWorkspace: { relationshipOwner: "Relationship owner", relationshipOwnerLabel: "Responsible team", relationshipAiParticipation: "AI participation", relationshipAiEnabled: "AI enabled", relationshipProtected: "Protected", relationshipOwnerChangeConfirm: "Change the owner? Pending work may be refreshed against the new BD configuration.", relationshipAiChangeConfirm: "Change AI participation? Pending work may be invalidated and rebuilt.", relationshipHumanOnlyHint: "{{name}} is human-only, so AI will not run for this relationship." } } },
  zh: { nav: { affiliateTeam: "团队与渠道" }, ecommerce: { affiliateTeam: zh, affiliateWorkspace: { relationshipOwner: "达人关系负责人", relationshipOwnerLabel: "负责团队", relationshipAiParticipation: "AI 参与", relationshipAiEnabled: "允许 AI", relationshipProtected: "受保护", relationshipOwnerChangeConfirm: "更换负责人？待处理工作可能会根据新 BD 配置重新生成。", relationshipAiChangeConfirm: "修改 AI 参与状态？现有待办可能会失效并重新生成。", relationshipHumanOnlyHint: "{{name}} 设置为仅人工处理，因此该达人关系不会触发 AI。" } } },
  de: { nav: { affiliateTeam: "Team & Kanäle" }, ecommerce: { affiliateTeam: de, affiliateWorkspace: { relationshipOwner: "Beziehungsverantwortlicher", relationshipOwnerLabel: "Zuständiges Team", relationshipAiParticipation: "KI-Beteiligung", relationshipAiEnabled: "KI aktiviert", relationshipProtected: "Geschützt", relationshipOwnerChangeConfirm: "Verantwortlichen ändern? Offene Arbeit kann aktualisiert werden.", relationshipAiChangeConfirm: "KI-Beteiligung ändern? Offene Arbeit kann neu erstellt werden.", relationshipHumanOnlyHint: "{{name}} arbeitet nur manuell; für diese Beziehung startet keine KI." } } },
  es: { nav: { affiliateTeam: "Equipo y canales" }, ecommerce: { affiliateTeam: es, affiliateWorkspace: { relationshipOwner: "Responsable de la relación", relationshipOwnerLabel: "Equipo responsable", relationshipAiParticipation: "Participación de IA", relationshipAiEnabled: "IA activada", relationshipProtected: "Protegida", relationshipOwnerChangeConfirm: "¿Cambiar responsable? El trabajo pendiente puede actualizarse.", relationshipAiChangeConfirm: "¿Cambiar la participación de IA? El trabajo pendiente puede regenerarse.", relationshipHumanOnlyHint: "{{name}} es solo humano; la IA no se ejecutará." } } },
  fr: { nav: { affiliateTeam: "Équipe et canaux" }, ecommerce: { affiliateTeam: fr, affiliateWorkspace: { relationshipOwner: "Responsable de la relation", relationshipOwnerLabel: "Équipe responsable", relationshipAiParticipation: "Participation de l'IA", relationshipAiEnabled: "IA activée", relationshipProtected: "Protégée", relationshipOwnerChangeConfirm: "Changer le responsable ? Le travail en attente peut être actualisé.", relationshipAiChangeConfirm: "Modifier la participation de l'IA ? Le travail peut être reconstruit.", relationshipHumanOnlyHint: "{{name}} est en mode humain uniquement ; l'IA ne sera pas lancée." } } },
  id: { nav: { affiliateTeam: "Tim & kanal" }, ecommerce: { affiliateTeam: id, affiliateWorkspace: { relationshipOwner: "Pemilik relasi", relationshipOwnerLabel: "Tim penanggung jawab", relationshipAiParticipation: "Partisipasi AI", relationshipAiEnabled: "AI aktif", relationshipProtected: "Dilindungi", relationshipOwnerChangeConfirm: "Ubah penanggung jawab? Pekerjaan tertunda dapat diperbarui.", relationshipAiChangeConfirm: "Ubah partisipasi AI? Pekerjaan tertunda dapat dibuat ulang.", relationshipHumanOnlyHint: "{{name}} hanya manusia; AI tidak akan berjalan." } } },
  it: { nav: { affiliateTeam: "Team e canali" }, ecommerce: { affiliateTeam: it, affiliateWorkspace: { relationshipOwner: "Responsabile della relazione", relationshipOwnerLabel: "Team responsabile", relationshipAiParticipation: "Partecipazione AI", relationshipAiEnabled: "AI attiva", relationshipProtected: "Protetta", relationshipOwnerChangeConfirm: "Cambiare responsabile? Il lavoro in attesa può essere aggiornato.", relationshipAiChangeConfirm: "Cambiare la partecipazione AI? Il lavoro può essere rigenerato.", relationshipHumanOnlyHint: "{{name}} è solo umano; l'AI non verrà eseguita." } } },
  th: { nav: { affiliateTeam: "ทีมและช่องทาง" }, ecommerce: { affiliateTeam: th, affiliateWorkspace: { relationshipOwner: "ผู้รับผิดชอบความสัมพันธ์", relationshipOwnerLabel: "ทีมที่รับผิดชอบ", relationshipAiParticipation: "การใช้ AI", relationshipAiEnabled: "เปิด AI", relationshipProtected: "ปกป้อง", relationshipOwnerChangeConfirm: "เปลี่ยนผู้รับผิดชอบหรือไม่ งานที่ค้างอาจถูกรีเฟรช", relationshipAiChangeConfirm: "เปลี่ยนการใช้ AI หรือไม่ งานที่ค้างอาจถูกสร้างใหม่", relationshipHumanOnlyHint: "{{name}} ตั้งเป็นคนดูแลเท่านั้น จึงไม่เรียกใช้ AI" } } },
} as const;
