const en = {
  whatsapp: {
    title: "WhatsApp outreach accounts", subtitle: "Linked-device accounts used for affiliate creator outreach.", connectorStatus: "Connector status", connectorStatusLoading: "Checking the WhatsApp connector.", connectorReady: "WhatsApp is ready for account onboarding.", connectorUnconfigured: "The WhatsApp connector is not configured.", connectorUnreachable: "The WhatsApp connector is unreachable.", connectorLicenseRequired: "The WhatsApp connector must be activated before onboarding.", connectorNotReady: "The WhatsApp connector is not ready.", connectedAccounts: "Connected", pendingAccounts: "Pending QR", activeProxies: "Active proxies", proxyLabel: "Proxy for new account", noProxy: "No proxy", connect: "Connect WhatsApp", proxyPool: "Proxy pool", proxyPoolHint: "Assign a stable egress proxy before scanning an account.", protocol: "Protocol", host: "Host", port: "Port", region: "Region", username: "Username", password: "Password", passwordKeep: "Leave blank to keep", addProxy: "Add proxy", noProxies: "No proxy configured yet.", proxyRequired: "Select or configure a proxy first.", proxyCreated: "Proxy created.", proxyUpdated: "Proxy updated.", refreshSuccess: "WhatsApp account refreshed.", accountConnected: "WhatsApp account connected.", empty: "No WhatsApp account connected yet.", qr: "QR code", qrAlt: "WhatsApp connection QR code", qrUnavailable: "QR code is not available.", scanTitle: "Scan with WhatsApp", scanHint: "Open Linked devices in WhatsApp and scan this code.", revoke: "Revoke", revokeSuccess: "WhatsApp account revoked.", bindingCreateFailed: "The WhatsApp account could not be created.",
    qrDataMissing: "The WhatsApp QR code could not be loaded.", status: { CONNECTED: "Connected", CONNECTING: "Connecting", PENDING_QR: "Pending QR", QR_PENDING: "Pending QR", DISCONNECTED: "Disconnected", ERROR: "Error", REVOKED: "Revoked" },
    proxyStatus: { ACTIVE: "Active", DISABLED: "Disabled", ERROR: "Error" },
  },
  email: {
    headline: "Outlook email accounts", hint: "Connect Microsoft mailboxes for creator outreach and inbound email sync.", connectorStatus: "Connector status", connectorStatusLoading: "Checking the Microsoft Graph connector.", connectorReady: "Microsoft Graph is ready for Outlook onboarding and inbound sync.", connectorUnconfigured: "Microsoft Graph OAuth and webhook settings are not configured.", connectorOAuthUnconfigured: "Microsoft Graph OAuth is not configured.", connectorWebhookUnconfigured: "Microsoft Graph webhooks are not configured.", connectorNotReady: "Microsoft Graph is not ready.", connectedAccounts: "Connected", activeSubscriptions: "Active subscriptions", missingSubscriptions: "Missing subscriptions", mailboxType: "Mailbox type", personalMailbox: "Personal mailbox", sharedMailbox: "Shared mailbox", sharedMailboxAddress: "Shared mailbox address", sharedMailboxRequired: "Enter the shared mailbox address.", nativeOutlookTitle: "Native Outlook.com account required", nativeOutlookOnly: "Sign in with an account whose Microsoft login and mailbox both end in @outlook.com. Gmail-based Microsoft accounts are rejected.", connect: "Connect Outlook", connecting: "Opening...", empty: "No Outlook mailbox connected yet.", updatedAt: "Updated", revoke: "Revoke", revokeSuccess: "Outlook account revoked.", oauthStarted: "Microsoft sign-in opened. This page will refresh after connection.", oauthCompleted: "Outlook mailbox connected.", oauthUrlMissing: "Microsoft sign-in could not be started.",
    status: { connected: "Connected", disconnected: "Disconnected", error: "Error", revoked: "Revoked" },
  },
} as const;

const zh = {
  whatsapp: {
    title: "WhatsApp 外联账号", subtitle: "用于 Affiliate 达人外联的已连接设备账号。", connectorStatus: "连接器状态", connectorStatusLoading: "正在检查 WhatsApp 连接器。", connectorReady: "WhatsApp 连接器已就绪，可以添加账号。", connectorUnconfigured: "尚未配置 WhatsApp 连接器。", connectorUnreachable: "无法连接 WhatsApp 连接器。", connectorLicenseRequired: "添加账号前需要先激活 WhatsApp 连接器。", connectorNotReady: "WhatsApp 连接器尚未就绪。", connectedAccounts: "已连接", pendingAccounts: "待扫码", activeProxies: "可用代理", proxyLabel: "新账号使用的代理", noProxy: "不使用代理", connect: "连接 WhatsApp", proxyPool: "代理池", proxyPoolHint: "扫描账号前，请为它分配一个稳定的出口代理。", protocol: "协议", host: "主机", port: "端口", region: "地区", username: "用户名", password: "密码", passwordKeep: "留空则保持不变", addProxy: "添加代理", noProxies: "尚未配置代理。", proxyRequired: "请先选择或配置代理。", proxyCreated: "代理已创建。", proxyUpdated: "代理已更新。", refreshSuccess: "WhatsApp 账号已刷新。", accountConnected: "WhatsApp 账号已连接。", empty: "尚未连接 WhatsApp 账号。", qr: "二维码", qrAlt: "WhatsApp 连接二维码", qrUnavailable: "暂时无法生成二维码。", scanTitle: "使用 WhatsApp 扫码", scanHint: "在 WhatsApp 中打开“已关联设备”，然后扫描此二维码。", revoke: "撤销连接", revokeSuccess: "WhatsApp 账号连接已撤销。", bindingCreateFailed: "无法创建 WhatsApp 账号连接。",
    qrDataMissing: "无法加载 WhatsApp 二维码。", status: { CONNECTED: "已连接", CONNECTING: "连接中", PENDING_QR: "待扫码", QR_PENDING: "待扫码", DISCONNECTED: "已断开", ERROR: "异常", REVOKED: "已撤销" },
    proxyStatus: { ACTIVE: "可用", DISABLED: "已停用", ERROR: "异常" },
  },
  email: {
    headline: "Outlook 邮箱账号", hint: "连接 Microsoft 邮箱，用于达人外联和入站邮件同步。", connectorStatus: "连接器状态", connectorStatusLoading: "正在检查 Microsoft Graph 连接器。", connectorReady: "Microsoft Graph 已就绪，可以连接 Outlook 并同步入站邮件。", connectorUnconfigured: "尚未配置 Microsoft Graph OAuth 和 Webhook。", connectorOAuthUnconfigured: "尚未配置 Microsoft Graph OAuth。", connectorWebhookUnconfigured: "尚未配置 Microsoft Graph Webhook。", connectorNotReady: "Microsoft Graph 连接器尚未就绪。", connectedAccounts: "已连接", activeSubscriptions: "有效订阅", missingSubscriptions: "缺失订阅", mailboxType: "邮箱类型", personalMailbox: "个人邮箱", sharedMailbox: "共享邮箱", sharedMailboxAddress: "共享邮箱地址", sharedMailboxRequired: "请输入共享邮箱地址。", nativeOutlookTitle: "仅支持原生 Outlook.com 账号", nativeOutlookOnly: "Microsoft 登录账号和邮箱都必须以 @outlook.com 结尾；使用 Gmail 注册的 Microsoft 账号会被拒绝。", connect: "连接 Outlook", connecting: "正在打开...", empty: "尚未连接 Outlook 邮箱。", updatedAt: "更新时间", revoke: "撤销连接", revokeSuccess: "Outlook 邮箱连接已撤销。", oauthStarted: "已打开 Microsoft 登录页，连接成功后本页会自动刷新。", oauthCompleted: "Outlook 邮箱已连接。", oauthUrlMissing: "无法启动 Microsoft 登录。",
    status: { connected: "已连接", disconnected: "已断开", error: "异常", revoked: "已撤销" },
  },
} as const;

const de = {
  whatsapp: {
    title: "WhatsApp-Konten für Outreach", subtitle: "Verknüpfte Geräte für die Kontaktaufnahme mit Creatorn.", connectorStatus: "Connector-Status", connectorStatusLoading: "WhatsApp-Connector wird geprüft.", connectorReady: "WhatsApp ist bereit, Konten hinzuzufügen.", connectorUnconfigured: "WhatsApp-Connector ist nicht konfiguriert.", connectorUnreachable: "WhatsApp-Connector ist nicht erreichbar.", connectorLicenseRequired: "WhatsApp-Connector muss zuerst aktiviert werden.", connectorNotReady: "WhatsApp-Connector ist nicht bereit.", connectedAccounts: "Verbunden", pendingAccounts: "QR ausstehend", activeProxies: "Aktive Proxys", proxyLabel: "Proxy für neues Konto", noProxy: "Kein Proxy", connect: "WhatsApp verbinden", proxyPool: "Proxy-Pool", proxyPoolHint: "Vor dem Scannen einen stabilen Ausgangsproxy zuweisen.", protocol: "Protokoll", host: "Host", port: "Port", region: "Region", username: "Benutzername", password: "Passwort", passwordKeep: "Leer lassen zum Beibehalten", addProxy: "Proxy hinzufügen", noProxies: "Noch kein Proxy konfiguriert.", proxyRequired: "Zuerst einen Proxy auswählen oder konfigurieren.", proxyCreated: "Proxy erstellt.", proxyUpdated: "Proxy aktualisiert.", refreshSuccess: "WhatsApp-Konto aktualisiert.", accountConnected: "WhatsApp-Konto verbunden.", empty: "Noch kein WhatsApp-Konto verbunden.", qr: "QR-Code", qrAlt: "QR-Code für WhatsApp-Verbindung", qrUnavailable: "QR-Code ist nicht verfügbar.", scanTitle: "Mit WhatsApp scannen", scanHint: "In WhatsApp Verknüpfte Geräte öffnen und den Code scannen.", revoke: "Widerrufen", revokeSuccess: "WhatsApp-Konto widerrufen.", bindingCreateFailed: "WhatsApp-Konto konnte nicht erstellt werden.",
    qrDataMissing: "Der WhatsApp-QR-Code konnte nicht geladen werden.", status: { CONNECTED: "Verbunden", CONNECTING: "Verbindung", PENDING_QR: "QR ausstehend", QR_PENDING: "QR ausstehend", DISCONNECTED: "Getrennt", ERROR: "Fehler", REVOKED: "Widerrufen" }, proxyStatus: { ACTIVE: "Aktiv", DISABLED: "Deaktiviert", ERROR: "Fehler" },
  },
  email: {
    headline: "Outlook-E-Mail-Konten", hint: "Microsoft-Postfächer für Creator-Outreach und eingehende E-Mails verbinden.", connectorStatus: "Connector-Status", connectorStatusLoading: "Microsoft Graph wird geprüft.", connectorReady: "Microsoft Graph ist für Outlook und Synchronisierung bereit.", connectorUnconfigured: "Microsoft Graph OAuth und Webhooks sind nicht konfiguriert.", connectorOAuthUnconfigured: "Microsoft Graph OAuth ist nicht konfiguriert.", connectorWebhookUnconfigured: "Microsoft Graph Webhooks sind nicht konfiguriert.", connectorNotReady: "Microsoft Graph ist nicht bereit.", connectedAccounts: "Verbunden", activeSubscriptions: "Aktive Abonnements", missingSubscriptions: "Fehlende Abonnements", mailboxType: "Postfachtyp", personalMailbox: "Persönliches Postfach", sharedMailbox: "Freigegebenes Postfach", sharedMailboxAddress: "Adresse des freigegebenen Postfachs", sharedMailboxRequired: "Adresse des freigegebenen Postfachs eingeben.", nativeOutlookTitle: "Natives Outlook.com-Konto erforderlich", nativeOutlookOnly: "Microsoft-Anmeldung und Postfach müssen auf @outlook.com enden. Mit Gmail registrierte Microsoft-Konten werden abgelehnt.", connect: "Outlook verbinden", connecting: "Wird geöffnet...", empty: "Noch kein Outlook-Postfach verbunden.", updatedAt: "Aktualisiert", revoke: "Widerrufen", revokeSuccess: "Outlook-Konto widerrufen.", oauthStarted: "Microsoft-Anmeldung geöffnet. Die Seite wird nach der Verbindung aktualisiert.", oauthCompleted: "Outlook-Postfach verbunden.", oauthUrlMissing: "Microsoft-Anmeldung konnte nicht gestartet werden.", status: { connected: "Verbunden", disconnected: "Getrennt", error: "Fehler", revoked: "Widerrufen" },
  },
} as const;

const es = {
  whatsapp: {
    title: "Cuentas de contacto de WhatsApp", subtitle: "Dispositivos vinculados para contactar con creadores.", connectorStatus: "Estado del conector", connectorStatusLoading: "Comprobando el conector de WhatsApp.", connectorReady: "WhatsApp está listo para añadir cuentas.", connectorUnconfigured: "El conector de WhatsApp no está configurado.", connectorUnreachable: "No se puede acceder al conector de WhatsApp.", connectorLicenseRequired: "Activa el conector de WhatsApp antes de continuar.", connectorNotReady: "El conector de WhatsApp no está listo.", connectedAccounts: "Conectadas", pendingAccounts: "QR pendiente", activeProxies: "Proxies activos", proxyLabel: "Proxy para la cuenta nueva", noProxy: "Sin proxy", connect: "Conectar WhatsApp", proxyPool: "Grupo de proxies", proxyPoolHint: "Asigna un proxy de salida estable antes de escanear una cuenta.", protocol: "Protocolo", host: "Host", port: "Puerto", region: "Región", username: "Usuario", password: "Contraseña", passwordKeep: "Déjalo vacío para conservarla", addProxy: "Añadir proxy", noProxies: "Aún no hay proxies.", proxyRequired: "Selecciona o configura un proxy.", proxyCreated: "Proxy creado.", proxyUpdated: "Proxy actualizado.", refreshSuccess: "Cuenta de WhatsApp actualizada.", accountConnected: "Cuenta de WhatsApp conectada.", empty: "No hay cuentas de WhatsApp conectadas.", qr: "Código QR", qrAlt: "Código QR para conectar WhatsApp", qrUnavailable: "El código QR no está disponible.", scanTitle: "Escanear con WhatsApp", scanHint: "Abre Dispositivos vinculados en WhatsApp y escanea el código.", revoke: "Revocar", revokeSuccess: "Cuenta de WhatsApp revocada.", bindingCreateFailed: "No se pudo crear la cuenta de WhatsApp.", qrDataMissing: "No se pudo cargar el código QR de WhatsApp.", status: { CONNECTED: "Conectada", CONNECTING: "Conectando", PENDING_QR: "QR pendiente", QR_PENDING: "QR pendiente", DISCONNECTED: "Desconectada", ERROR: "Error", REVOKED: "Revocada" }, proxyStatus: { ACTIVE: "Activo", DISABLED: "Desactivado", ERROR: "Error" },
  },
  email: {
    headline: "Cuentas de correo de Outlook", hint: "Conecta buzones de Microsoft para contactar y sincronizar correos.", connectorStatus: "Estado del conector", connectorStatusLoading: "Comprobando Microsoft Graph.", connectorReady: "Microsoft Graph está listo para Outlook y la sincronización.", connectorUnconfigured: "OAuth y los webhooks de Microsoft Graph no están configurados.", connectorOAuthUnconfigured: "OAuth de Microsoft Graph no está configurado.", connectorWebhookUnconfigured: "Los webhooks de Microsoft Graph no están configurados.", connectorNotReady: "Microsoft Graph no está listo.", connectedAccounts: "Conectadas", activeSubscriptions: "Suscripciones activas", missingSubscriptions: "Suscripciones ausentes", mailboxType: "Tipo de buzón", personalMailbox: "Buzón personal", sharedMailbox: "Buzón compartido", sharedMailboxAddress: "Dirección del buzón compartido", sharedMailboxRequired: "Introduce la dirección del buzón compartido.", nativeOutlookTitle: "Se requiere una cuenta nativa de Outlook.com", nativeOutlookOnly: "El inicio de sesión y el buzón de Microsoft deben terminar en @outlook.com. Se rechazan cuentas Microsoft registradas con Gmail.", connect: "Conectar Outlook", connecting: "Abriendo...", empty: "No hay buzones de Outlook conectados.", updatedAt: "Actualizado", revoke: "Revocar", revokeSuccess: "Cuenta de Outlook revocada.", oauthStarted: "Se abrió el inicio de sesión de Microsoft. La página se actualizará al conectar.", oauthCompleted: "Buzón de Outlook conectado.", oauthUrlMissing: "No se pudo iniciar sesión con Microsoft.", status: { connected: "Conectada", disconnected: "Desconectada", error: "Error", revoked: "Revocada" },
  },
} as const;

const fr = {
  whatsapp: {
    title: "Comptes WhatsApp de prospection", subtitle: "Appareils liés utilisés pour contacter les créateurs.", connectorStatus: "État du connecteur", connectorStatusLoading: "Vérification du connecteur WhatsApp.", connectorReady: "WhatsApp est prêt à ajouter des comptes.", connectorUnconfigured: "Le connecteur WhatsApp n'est pas configuré.", connectorUnreachable: "Le connecteur WhatsApp est inaccessible.", connectorLicenseRequired: "Activez le connecteur WhatsApp avant de continuer.", connectorNotReady: "Le connecteur WhatsApp n'est pas prêt.", connectedAccounts: "Connectés", pendingAccounts: "QR en attente", activeProxies: "Proxys actifs", proxyLabel: "Proxy du nouveau compte", noProxy: "Aucun proxy", connect: "Connecter WhatsApp", proxyPool: "Pool de proxys", proxyPoolHint: "Attribuez un proxy de sortie stable avant de scanner un compte.", protocol: "Protocole", host: "Hôte", port: "Port", region: "Région", username: "Nom d'utilisateur", password: "Mot de passe", passwordKeep: "Laisser vide pour conserver", addProxy: "Ajouter un proxy", noProxies: "Aucun proxy configuré.", proxyRequired: "Sélectionnez ou configurez d'abord un proxy.", proxyCreated: "Proxy créé.", proxyUpdated: "Proxy mis à jour.", refreshSuccess: "Compte WhatsApp actualisé.", accountConnected: "Compte WhatsApp connecté.", empty: "Aucun compte WhatsApp connecté.", qr: "Code QR", qrAlt: "Code QR de connexion WhatsApp", qrUnavailable: "Le code QR n'est pas disponible.", scanTitle: "Scanner avec WhatsApp", scanHint: "Ouvrez Appareils connectés dans WhatsApp et scannez ce code.", revoke: "Révoquer", revokeSuccess: "Compte WhatsApp révoqué.", bindingCreateFailed: "Le compte WhatsApp n'a pas pu être créé.", qrDataMissing: "Le code QR WhatsApp n'a pas pu être chargé.", status: { CONNECTED: "Connecté", CONNECTING: "Connexion", PENDING_QR: "QR en attente", QR_PENDING: "QR en attente", DISCONNECTED: "Déconnecté", ERROR: "Erreur", REVOKED: "Révoqué" }, proxyStatus: { ACTIVE: "Actif", DISABLED: "Désactivé", ERROR: "Erreur" },
  },
  email: {
    headline: "Comptes e-mail Outlook", hint: "Connectez des boîtes Microsoft pour la prospection et la synchronisation.", connectorStatus: "État du connecteur", connectorStatusLoading: "Vérification de Microsoft Graph.", connectorReady: "Microsoft Graph est prêt pour Outlook et la synchronisation.", connectorUnconfigured: "OAuth et les webhooks Microsoft Graph ne sont pas configurés.", connectorOAuthUnconfigured: "OAuth Microsoft Graph n'est pas configuré.", connectorWebhookUnconfigured: "Les webhooks Microsoft Graph ne sont pas configurés.", connectorNotReady: "Microsoft Graph n'est pas prêt.", connectedAccounts: "Connectés", activeSubscriptions: "Abonnements actifs", missingSubscriptions: "Abonnements manquants", mailboxType: "Type de boîte", personalMailbox: "Boîte personnelle", sharedMailbox: "Boîte partagée", sharedMailboxAddress: "Adresse de la boîte partagée", sharedMailboxRequired: "Saisissez l'adresse de la boîte partagée.", nativeOutlookTitle: "Compte Outlook.com natif requis", nativeOutlookOnly: "La connexion Microsoft et la boîte doivent se terminer par @outlook.com. Les comptes Microsoft créés avec Gmail sont refusés.", connect: "Connecter Outlook", connecting: "Ouverture...", empty: "Aucune boîte Outlook connectée.", updatedAt: "Mis à jour", revoke: "Révoquer", revokeSuccess: "Compte Outlook révoqué.", oauthStarted: "Connexion Microsoft ouverte. La page sera actualisée après la connexion.", oauthCompleted: "Boîte Outlook connectée.", oauthUrlMissing: "Impossible de lancer la connexion Microsoft.", status: { connected: "Connecté", disconnected: "Déconnecté", error: "Erreur", revoked: "Révoqué" },
  },
} as const;

const id = {
  whatsapp: {
    title: "Akun outreach WhatsApp", subtitle: "Perangkat tertaut untuk menghubungi kreator afiliasi.", connectorStatus: "Status konektor", connectorStatusLoading: "Memeriksa konektor WhatsApp.", connectorReady: "WhatsApp siap menambahkan akun.", connectorUnconfigured: "Konektor WhatsApp belum dikonfigurasi.", connectorUnreachable: "Konektor WhatsApp tidak dapat dijangkau.", connectorLicenseRequired: "Aktifkan konektor WhatsApp sebelum melanjutkan.", connectorNotReady: "Konektor WhatsApp belum siap.", connectedAccounts: "Terhubung", pendingAccounts: "QR tertunda", activeProxies: "Proxy aktif", proxyLabel: "Proxy akun baru", noProxy: "Tanpa proxy", connect: "Hubungkan WhatsApp", proxyPool: "Kumpulan proxy", proxyPoolHint: "Tetapkan proxy keluar yang stabil sebelum memindai akun.", protocol: "Protokol", host: "Host", port: "Port", region: "Wilayah", username: "Nama pengguna", password: "Kata sandi", passwordKeep: "Kosongkan untuk mempertahankan", addProxy: "Tambah proxy", noProxies: "Belum ada proxy.", proxyRequired: "Pilih atau atur proxy terlebih dahulu.", proxyCreated: "Proxy dibuat.", proxyUpdated: "Proxy diperbarui.", refreshSuccess: "Akun WhatsApp diperbarui.", accountConnected: "Akun WhatsApp terhubung.", empty: "Belum ada akun WhatsApp.", qr: "Kode QR", qrAlt: "Kode QR koneksi WhatsApp", qrUnavailable: "Kode QR tidak tersedia.", scanTitle: "Pindai dengan WhatsApp", scanHint: "Buka Perangkat tertaut di WhatsApp lalu pindai kode ini.", revoke: "Cabut", revokeSuccess: "Akun WhatsApp dicabut.", bindingCreateFailed: "Akun WhatsApp tidak dapat dibuat.", qrDataMissing: "Kode QR WhatsApp tidak dapat dimuat.", status: { CONNECTED: "Terhubung", CONNECTING: "Menghubungkan", PENDING_QR: "QR tertunda", QR_PENDING: "QR tertunda", DISCONNECTED: "Terputus", ERROR: "Error", REVOKED: "Dicabut" }, proxyStatus: { ACTIVE: "Aktif", DISABLED: "Dinonaktifkan", ERROR: "Error" },
  },
  email: {
    headline: "Akun email Outlook", hint: "Hubungkan kotak surat Microsoft untuk outreach dan sinkronisasi email.", connectorStatus: "Status konektor", connectorStatusLoading: "Memeriksa Microsoft Graph.", connectorReady: "Microsoft Graph siap untuk Outlook dan sinkronisasi.", connectorUnconfigured: "OAuth dan webhook Microsoft Graph belum dikonfigurasi.", connectorOAuthUnconfigured: "OAuth Microsoft Graph belum dikonfigurasi.", connectorWebhookUnconfigured: "Webhook Microsoft Graph belum dikonfigurasi.", connectorNotReady: "Microsoft Graph belum siap.", connectedAccounts: "Terhubung", activeSubscriptions: "Langganan aktif", missingSubscriptions: "Langganan hilang", mailboxType: "Jenis kotak surat", personalMailbox: "Kotak surat pribadi", sharedMailbox: "Kotak surat bersama", sharedMailboxAddress: "Alamat kotak surat bersama", sharedMailboxRequired: "Masukkan alamat kotak surat bersama.", nativeOutlookTitle: "Wajib akun Outlook.com asli", nativeOutlookOnly: "Login Microsoft dan kotak surat harus berakhiran @outlook.com. Akun Microsoft yang dibuat dengan Gmail akan ditolak.", connect: "Hubungkan Outlook", connecting: "Membuka...", empty: "Belum ada kotak surat Outlook.", updatedAt: "Diperbarui", revoke: "Cabut", revokeSuccess: "Akun Outlook dicabut.", oauthStarted: "Login Microsoft dibuka. Halaman akan diperbarui setelah terhubung.", oauthCompleted: "Kotak surat Outlook terhubung.", oauthUrlMissing: "Login Microsoft tidak dapat dimulai.", status: { connected: "Terhubung", disconnected: "Terputus", error: "Error", revoked: "Dicabut" },
  },
} as const;

const it = {
  whatsapp: {
    title: "Account WhatsApp per contatti", subtitle: "Dispositivi collegati usati per contattare i creator.", connectorStatus: "Stato connettore", connectorStatusLoading: "Verifica del connettore WhatsApp.", connectorReady: "WhatsApp è pronto per aggiungere account.", connectorUnconfigured: "Il connettore WhatsApp non è configurato.", connectorUnreachable: "Il connettore WhatsApp non è raggiungibile.", connectorLicenseRequired: "Attiva il connettore WhatsApp prima di continuare.", connectorNotReady: "Il connettore WhatsApp non è pronto.", connectedAccounts: "Collegati", pendingAccounts: "QR in attesa", activeProxies: "Proxy attivi", proxyLabel: "Proxy per il nuovo account", noProxy: "Nessun proxy", connect: "Collega WhatsApp", proxyPool: "Pool di proxy", proxyPoolHint: "Assegna un proxy di uscita stabile prima di scansionare un account.", protocol: "Protocollo", host: "Host", port: "Porta", region: "Regione", username: "Nome utente", password: "Password", passwordKeep: "Lascia vuoto per mantenere", addProxy: "Aggiungi proxy", noProxies: "Nessun proxy configurato.", proxyRequired: "Seleziona o configura prima un proxy.", proxyCreated: "Proxy creato.", proxyUpdated: "Proxy aggiornato.", refreshSuccess: "Account WhatsApp aggiornato.", accountConnected: "Account WhatsApp collegato.", empty: "Nessun account WhatsApp collegato.", qr: "Codice QR", qrAlt: "Codice QR di connessione WhatsApp", qrUnavailable: "Codice QR non disponibile.", scanTitle: "Scansiona con WhatsApp", scanHint: "Apri Dispositivi collegati in WhatsApp e scansiona il codice.", revoke: "Revoca", revokeSuccess: "Account WhatsApp revocato.", bindingCreateFailed: "Impossibile creare l'account WhatsApp.", qrDataMissing: "Impossibile caricare il codice QR di WhatsApp.", status: { CONNECTED: "Collegato", CONNECTING: "Connessione", PENDING_QR: "QR in attesa", QR_PENDING: "QR in attesa", DISCONNECTED: "Disconnesso", ERROR: "Errore", REVOKED: "Revocato" }, proxyStatus: { ACTIVE: "Attivo", DISABLED: "Disattivato", ERROR: "Errore" },
  },
  email: {
    headline: "Account e-mail Outlook", hint: "Collega caselle Microsoft per contatti e sincronizzazione e-mail.", connectorStatus: "Stato connettore", connectorStatusLoading: "Verifica di Microsoft Graph.", connectorReady: "Microsoft Graph è pronto per Outlook e la sincronizzazione.", connectorUnconfigured: "OAuth e webhook Microsoft Graph non sono configurati.", connectorOAuthUnconfigured: "OAuth Microsoft Graph non è configurato.", connectorWebhookUnconfigured: "I webhook Microsoft Graph non sono configurati.", connectorNotReady: "Microsoft Graph non è pronto.", connectedAccounts: "Collegati", activeSubscriptions: "Sottoscrizioni attive", missingSubscriptions: "Sottoscrizioni mancanti", mailboxType: "Tipo di casella", personalMailbox: "Casella personale", sharedMailbox: "Casella condivisa", sharedMailboxAddress: "Indirizzo casella condivisa", sharedMailboxRequired: "Inserisci l'indirizzo della casella condivisa.", nativeOutlookTitle: "È richiesto un account Outlook.com nativo", nativeOutlookOnly: "L'accesso Microsoft e la casella devono terminare con @outlook.com. Gli account Microsoft registrati con Gmail vengono rifiutati.", connect: "Collega Outlook", connecting: "Apertura...", empty: "Nessuna casella Outlook collegata.", updatedAt: "Aggiornato", revoke: "Revoca", revokeSuccess: "Account Outlook revocato.", oauthStarted: "Accesso Microsoft aperto. La pagina si aggiornerà dopo il collegamento.", oauthCompleted: "Casella Outlook collegata.", oauthUrlMissing: "Impossibile avviare l'accesso Microsoft.", status: { connected: "Collegato", disconnected: "Disconnesso", error: "Errore", revoked: "Revocato" },
  },
} as const;

const th = {
  whatsapp: {
    title: "บัญชี WhatsApp สำหรับติดต่อนักสร้างสรรค์", subtitle: "อุปกรณ์ที่เชื่อมโยงสำหรับงาน Affiliate", connectorStatus: "สถานะตัวเชื่อมต่อ", connectorStatusLoading: "กำลังตรวจสอบ WhatsApp", connectorReady: "WhatsApp พร้อมเพิ่มบัญชี", connectorUnconfigured: "ยังไม่ได้ตั้งค่าตัวเชื่อมต่อ WhatsApp", connectorUnreachable: "ไม่สามารถเข้าถึงตัวเชื่อมต่อ WhatsApp", connectorLicenseRequired: "โปรดเปิดใช้งานตัวเชื่อมต่อ WhatsApp ก่อน", connectorNotReady: "ตัวเชื่อมต่อ WhatsApp ยังไม่พร้อม", connectedAccounts: "เชื่อมต่อแล้ว", pendingAccounts: "รอสแกน QR", activeProxies: "พร็อกซีที่ใช้งาน", proxyLabel: "พร็อกซีสำหรับบัญชีใหม่", noProxy: "ไม่ใช้พร็อกซี", connect: "เชื่อมต่อ WhatsApp", proxyPool: "คลังพร็อกซี", proxyPoolHint: "กำหนดพร็อกซีขาออกที่เสถียรก่อนสแกนบัญชี", protocol: "โปรโตคอล", host: "โฮสต์", port: "พอร์ต", region: "ภูมิภาค", username: "ชื่อผู้ใช้", password: "รหัสผ่าน", passwordKeep: "เว้นว่างเพื่อใช้ค่าเดิม", addProxy: "เพิ่มพร็อกซี", noProxies: "ยังไม่มีพร็อกซี", proxyRequired: "เลือกหรือตั้งค่าพร็อกซีก่อน", proxyCreated: "สร้างพร็อกซีแล้ว", proxyUpdated: "อัปเดตพร็อกซีแล้ว", refreshSuccess: "รีเฟรชบัญชี WhatsApp แล้ว", accountConnected: "เชื่อมต่อบัญชี WhatsApp แล้ว", empty: "ยังไม่มีบัญชี WhatsApp", qr: "คิวอาร์โค้ด", qrAlt: "คิวอาร์โค้ดเชื่อมต่อ WhatsApp", qrUnavailable: "ไม่มีคิวอาร์โค้ด", scanTitle: "สแกนด้วย WhatsApp", scanHint: "เปิดอุปกรณ์ที่เชื่อมโยงใน WhatsApp แล้วสแกนรหัสนี้", revoke: "ยกเลิกการเชื่อมต่อ", revokeSuccess: "ยกเลิกบัญชี WhatsApp แล้ว", bindingCreateFailed: "ไม่สามารถสร้างบัญชี WhatsApp", qrDataMissing: "ไม่สามารถโหลดคิวอาร์โค้ด WhatsApp", status: { CONNECTED: "เชื่อมต่อแล้ว", CONNECTING: "กำลังเชื่อมต่อ", PENDING_QR: "รอสแกน QR", QR_PENDING: "รอสแกน QR", DISCONNECTED: "ตัดการเชื่อมต่อ", ERROR: "ผิดพลาด", REVOKED: "ยกเลิกแล้ว" }, proxyStatus: { ACTIVE: "ใช้งาน", DISABLED: "ปิดใช้งาน", ERROR: "ผิดพลาด" },
  },
  email: {
    headline: "บัญชีอีเมล Outlook", hint: "เชื่อมต่อกล่องจดหมาย Microsoft สำหรับการติดต่อและซิงค์อีเมล", connectorStatus: "สถานะตัวเชื่อมต่อ", connectorStatusLoading: "กำลังตรวจสอบ Microsoft Graph", connectorReady: "Microsoft Graph พร้อมใช้งาน Outlook และการซิงค์", connectorUnconfigured: "ยังไม่ได้ตั้งค่า OAuth และ webhook ของ Microsoft Graph", connectorOAuthUnconfigured: "ยังไม่ได้ตั้งค่า OAuth ของ Microsoft Graph", connectorWebhookUnconfigured: "ยังไม่ได้ตั้งค่า webhook ของ Microsoft Graph", connectorNotReady: "Microsoft Graph ยังไม่พร้อม", connectedAccounts: "เชื่อมต่อแล้ว", activeSubscriptions: "การสมัครที่ใช้งาน", missingSubscriptions: "การสมัครที่ขาดหาย", mailboxType: "ประเภทกล่องจดหมาย", personalMailbox: "กล่องจดหมายส่วนตัว", sharedMailbox: "กล่องจดหมายร่วม", sharedMailboxAddress: "ที่อยู่กล่องจดหมายร่วม", sharedMailboxRequired: "กรอกที่อยู่กล่องจดหมายร่วม", nativeOutlookTitle: "ต้องใช้บัญชี Outlook.com แบบดั้งเดิม", nativeOutlookOnly: "บัญชี Microsoft และกล่องจดหมายต้องลงท้ายด้วย @outlook.com ระบบจะปฏิเสธบัญชี Microsoft ที่สมัครด้วย Gmail", connect: "เชื่อมต่อ Outlook", connecting: "กำลังเปิด...", empty: "ยังไม่มีกล่องจดหมาย Outlook", updatedAt: "อัปเดต", revoke: "ยกเลิก", revokeSuccess: "ยกเลิกบัญชี Outlook แล้ว", oauthStarted: "เปิดการเข้าสู่ระบบ Microsoft แล้ว หน้านี้จะรีเฟรชหลังเชื่อมต่อ", oauthCompleted: "เชื่อมต่อกล่องจดหมาย Outlook แล้ว", oauthUrlMissing: "ไม่สามารถเริ่มการเข้าสู่ระบบ Microsoft", status: { connected: "เชื่อมต่อแล้ว", disconnected: "ตัดการเชื่อมต่อ", error: "ผิดพลาด", revoked: "ยกเลิกแล้ว" },
  },
} as const;

export const AFFILIATE_CHANNEL_TRANSLATIONS = {
  en: { ecommerce: { affiliateWorkspace: en } },
  zh: { ecommerce: { affiliateWorkspace: zh } },
  de: { ecommerce: { affiliateWorkspace: de } },
  es: { ecommerce: { affiliateWorkspace: es } },
  fr: { ecommerce: { affiliateWorkspace: fr } },
  id: { ecommerce: { affiliateWorkspace: id } },
  it: { ecommerce: { affiliateWorkspace: it } },
  th: { ecommerce: { affiliateWorkspace: th } },
} as const;
