const en = {
  eyebrow: "Affiliate operations", title: "Team & channels", subtitle: "Assign creator relationships and outreach accounts to the people responsible for moving them forward.",
  addDeveloper: "Add BD", aiTeam: "AI team", aiTeamHint: "Unassigned relationships", aiTeamDescription: "The AI team handles eligible creator relationships that are not assigned to a human BD.",
  businessDeveloper: "Business developer", virtualOwner: "Default owner", developerHint: "This BD's working mode and instructions apply to every assigned creator relationship.",
  roster: "Owners", workMode: "Work mode", aiAssisted: "AI assisted", humanOnly: "Human only", aiManaged: "AI managed", acceptingCreators: "Accepting new creators",
  whatsappAccounts: "WhatsApp accounts", emailAccounts: "Email accounts", channels: "Channels", connectChannel: "Connect channel", noChannels: "No outreach accounts are assigned to this owner.", unnamedAccount: "Unnamed account",
  workingStyle: "Working style", workingStylePlaceholder: "Describe this BD's tone, priorities, negotiation habits, and handoff preferences.", regions: "Regions", name: "Name", newDeveloper: "New business developer", nameRequired: "Enter a BD name.", saved: "BD settings saved.",
  archive: "Archive", archiveConfirm: "Archive {{name}}? Reassign their creators and accounts first.", archived: "BD archived.", transferConfirm: "Move this account? Related creator channels will be rebound and pending work may be refreshed.", accountMoved: "Account owner updated.",
  onboardingStep: "Affiliate setup", onboardingTitle: "Protect existing BD relationships before AI starts", onboardingHint: "Import creators your current team already manages. Unlisted, unassigned relationships become eligible for the AI team after confirmation.",
  downloadTemplate: "Download template", importProtected: "Import protected creators", importPreview: "Import preview", importValid: "Import {{count}} valid rows", protectedOnly: "Protected only", ready: "Ready",
  creatorIdentity: "Creator identity", creatorIdentityPlaceholder: "@username or creator open ID", assignDeveloper: "Responsible BD", note: "Note", notePlaceholder: "Why this relationship is protected", addProtectedCreator: "Add protected creator",
  emptySpreadsheet: "The spreadsheet has no readable worksheet.", missingCreatorIdentity: "Provide creator_open_id or username.", duplicateCreator: "Duplicate creator in this file.", unknownDeveloper: "BD “{{name}}” does not exist.", protectionsImported: "Imported {{count}} protected creators.",
  confirmBoundary: "I reviewed the protected creator list. Relationships that are not protected and not assigned to a human BD may be handled by the AI team.", completeSetup: "Complete setup and enable AI", onboardingCompleted: "Affiliate operational setup completed.",
} as const;

const zh = {
  eyebrow: "Affiliate 运营", title: "团队与渠道", subtitle: "把达人关系和联络渠道分配给真正负责推进合作的人。",
  addDeveloper: "新增 BD", aiTeam: "AI 团队", aiTeamHint: "未分配的达人关系", aiTeamDescription: "AI 团队负责所有未分配给人工 BD 且允许 AI 参与的达人关系。",
  businessDeveloper: "商务开发", virtualOwner: "默认负责人", developerHint: "该 BD 的工作模式和业务习惯会作用于名下所有达人关系。",
  roster: "负责人", workMode: "工作模式", aiAssisted: "AI 辅助", humanOnly: "仅人工处理", aiManaged: "AI 管理", acceptingCreators: "接收新达人",
  whatsappAccounts: "WhatsApp 账号", emailAccounts: "邮箱账号", channels: "联络渠道", connectChannel: "连接渠道", noChannels: "该负责人尚未分配任何联络账号。", unnamedAccount: "未命名账号",
  workingStyle: "工作习惯", workingStylePlaceholder: "描述该 BD 的沟通语气、业务重点、议价习惯和交接偏好。", regions: "负责地区", name: "姓名", newDeveloper: "新增商务开发", nameRequired: "请输入 BD 姓名。", saved: "BD 设置已保存。",
  archive: "归档", archiveConfirm: "归档 {{name}}？请先转移其达人关系和账号。", archived: "BD 已归档。", transferConfirm: "转移这个账号？相关达人渠道会重新归属，待处理工作也可能刷新。", accountMoved: "账号负责人已更新。",
  onboardingStep: "Affiliate 初始化", onboardingTitle: "在 AI 开始工作前保护现有 BD 关系", onboardingHint: "导入目前由人工团队维护的达人。确认后，未被保护且未分配人工 BD 的关系将由 AI 团队处理。",
  downloadTemplate: "下载模板", importProtected: "导入受保护达人", importPreview: "导入预览", importValid: "导入 {{count}} 条有效记录", protectedOnly: "仅保护", ready: "可导入",
  creatorIdentity: "达人身份", creatorIdentityPlaceholder: "@用户名或达人 Open ID", assignDeveloper: "负责 BD", note: "备注", notePlaceholder: "说明保护这段关系的原因", addProtectedCreator: "添加受保护达人",
  emptySpreadsheet: "表格中没有可读取的工作表。", missingCreatorIdentity: "请填写 creator_open_id 或 username。", duplicateCreator: "文件中达人重复。", unknownDeveloper: "BD“{{name}}”不存在。", protectionsImported: "已导入 {{count}} 个受保护达人。",
  confirmBoundary: "我已检查受保护达人名单；未被保护且未分配人工 BD 的达人关系可以由 AI 团队处理。", completeSetup: "完成设置并启用 AI", onboardingCompleted: "Affiliate 运营设置已完成。",
} as const;

const de = {
  eyebrow: "Affiliate-Betrieb", title: "Team & Kanäle", subtitle: "Creator-Beziehungen und Kontaktkonten den zuständigen Personen zuweisen.", addDeveloper: "BD hinzufügen", aiTeam: "KI-Team", aiTeamHint: "Nicht zugewiesene Beziehungen", aiTeamDescription: "Das KI-Team bearbeitet geeignete Beziehungen ohne menschlichen BD.", businessDeveloper: "Business Developer", virtualOwner: "Standardverantwortlicher", developerHint: "Arbeitsmodus und Anweisungen gelten für alle zugewiesenen Creator.", roster: "Verantwortliche", workMode: "Arbeitsmodus", aiAssisted: "KI-unterstützt", humanOnly: "Nur manuell", aiManaged: "KI-verwaltet", acceptingCreators: "Nimmt neue Creator an", whatsappAccounts: "WhatsApp-Konten", emailAccounts: "E-Mail-Konten", channels: "Kanäle", connectChannel: "Kanal verbinden", noChannels: "Keine Kontaktkonten zugewiesen.", unnamedAccount: "Unbenanntes Konto", workingStyle: "Arbeitsweise", workingStylePlaceholder: "Ton, Prioritäten, Verhandlungs- und Übergabegewohnheiten beschreiben.", regions: "Regionen", name: "Name", newDeveloper: "Neuer Business Developer", nameRequired: "BD-Namen eingeben.", saved: "BD-Einstellungen gespeichert.", archive: "Archivieren", archiveConfirm: "{{name}} archivieren? Creator und Konten zuerst neu zuweisen.", archived: "BD archiviert.", transferConfirm: "Konto verschieben? Zugehörige Kanäle und offene Arbeit werden aktualisiert.", accountMoved: "Kontoinhaber aktualisiert.", onboardingStep: "Affiliate-Einrichtung", onboardingTitle: "Bestehende BD-Beziehungen vor dem KI-Start schützen", onboardingHint: "Bereits betreute Creator importieren. Andere nicht zugewiesene Beziehungen werden nach Bestätigung KI-fähig.", downloadTemplate: "Vorlage laden", importProtected: "Geschützte Creator importieren", importPreview: "Importvorschau", importValid: "{{count}} gültige Zeilen importieren", protectedOnly: "Nur geschützt", ready: "Bereit", creatorIdentity: "Creator-Identität", creatorIdentityPlaceholder: "@Username oder Open ID", assignDeveloper: "Zuständiger BD", note: "Notiz", notePlaceholder: "Grund für den Schutz", addProtectedCreator: "Creator schützen", emptySpreadsheet: "Keine lesbare Tabelle gefunden.", missingCreatorIdentity: "creator_open_id oder username angeben.", duplicateCreator: "Creator ist doppelt vorhanden.", unknownDeveloper: "BD „{{name}}“ existiert nicht.", protectionsImported: "{{count}} geschützte Creator importiert.", confirmBoundary: "Ich habe die Schutzliste geprüft. Nicht geschützte, nicht zugewiesene Beziehungen darf das KI-Team bearbeiten.", completeSetup: "Einrichtung abschließen und KI aktivieren", onboardingCompleted: "Affiliate-Einrichtung abgeschlossen.",
} as const;

const es = {
  eyebrow: "Operaciones de afiliados", title: "Equipo y canales", subtitle: "Asigna relaciones y cuentas de contacto a las personas responsables.", addDeveloper: "Añadir BD", aiTeam: "Equipo de IA", aiTeamHint: "Relaciones sin asignar", aiTeamDescription: "El equipo de IA gestiona relaciones aptas sin un BD humano.", businessDeveloper: "Desarrollo de negocio", virtualOwner: "Responsable predeterminado", developerHint: "El modo y las instrucciones del BD se aplican a sus creadores.", roster: "Responsables", workMode: "Modo de trabajo", aiAssisted: "Asistido por IA", humanOnly: "Solo humano", aiManaged: "Gestionado por IA", acceptingCreators: "Acepta nuevos creadores", whatsappAccounts: "Cuentas de WhatsApp", emailAccounts: "Cuentas de correo", channels: "Canales", connectChannel: "Conectar canal", noChannels: "No hay cuentas asignadas.", unnamedAccount: "Cuenta sin nombre", workingStyle: "Estilo de trabajo", workingStylePlaceholder: "Describe tono, prioridades, negociación y traspasos.", regions: "Regiones", name: "Nombre", newDeveloper: "Nuevo BD", nameRequired: "Introduce el nombre del BD.", saved: "Configuración guardada.", archive: "Archivar", archiveConfirm: "¿Archivar a {{name}}? Reasigna antes sus creadores y cuentas.", archived: "BD archivado.", transferConfirm: "¿Mover esta cuenta? Se reasignarán canales y trabajos pendientes.", accountMoved: "Responsable actualizado.", onboardingStep: "Configuración de afiliados", onboardingTitle: "Protege relaciones existentes antes de activar la IA", onboardingHint: "Importa creadores ya gestionados. Los demás podrán pasar al equipo de IA.", downloadTemplate: "Descargar plantilla", importProtected: "Importar protegidos", importPreview: "Vista previa", importValid: "Importar {{count}} filas válidas", protectedOnly: "Solo protegido", ready: "Listo", creatorIdentity: "Identidad del creador", creatorIdentityPlaceholder: "@usuario u Open ID", assignDeveloper: "BD responsable", note: "Nota", notePlaceholder: "Motivo de protección", addProtectedCreator: "Proteger creador", emptySpreadsheet: "La hoja no contiene datos legibles.", missingCreatorIdentity: "Indica creator_open_id o username.", duplicateCreator: "Creador duplicado.", unknownDeveloper: "El BD «{{name}}» no existe.", protectionsImported: "Se importaron {{count}} creadores protegidos.", confirmBoundary: "He revisado la lista. El equipo de IA puede gestionar relaciones no protegidas y sin BD humano.", completeSetup: "Completar y activar IA", onboardingCompleted: "Configuración completada.",
} as const;

const fr = {
  eyebrow: "Opérations d'affiliation", title: "Équipe et canaux", subtitle: "Attribuez les relations et comptes de contact aux responsables.", addDeveloper: "Ajouter un BD", aiTeam: "Équipe IA", aiTeamHint: "Relations non attribuées", aiTeamDescription: "L'équipe IA gère les relations éligibles sans BD humain.", businessDeveloper: "Business developer", virtualOwner: "Responsable par défaut", developerHint: "Le mode et les consignes du BD s'appliquent à ses créateurs.", roster: "Responsables", workMode: "Mode de travail", aiAssisted: "Assisté par IA", humanOnly: "Humain uniquement", aiManaged: "Géré par IA", acceptingCreators: "Accepte de nouveaux créateurs", whatsappAccounts: "Comptes WhatsApp", emailAccounts: "Comptes e-mail", channels: "Canaux", connectChannel: "Connecter un canal", noChannels: "Aucun compte attribué.", unnamedAccount: "Compte sans nom", workingStyle: "Méthode de travail", workingStylePlaceholder: "Décrivez ton, priorités, négociation et transmission.", regions: "Régions", name: "Nom", newDeveloper: "Nouveau BD", nameRequired: "Saisissez le nom du BD.", saved: "Paramètres enregistrés.", archive: "Archiver", archiveConfirm: "Archiver {{name}} ? Réattribuez d'abord ses créateurs et comptes.", archived: "BD archivé.", transferConfirm: "Déplacer ce compte ? Les canaux et travaux associés seront actualisés.", accountMoved: "Responsable du compte mis à jour.", onboardingStep: "Configuration Affiliate", onboardingTitle: "Protégez les relations existantes avant l'IA", onboardingHint: "Importez les créateurs déjà suivis. Les autres pourront être gérés par l'équipe IA.", downloadTemplate: "Télécharger le modèle", importProtected: "Importer les créateurs protégés", importPreview: "Aperçu", importValid: "Importer {{count}} lignes valides", protectedOnly: "Protection seule", ready: "Prêt", creatorIdentity: "Identité du créateur", creatorIdentityPlaceholder: "@identifiant ou Open ID", assignDeveloper: "BD responsable", note: "Note", notePlaceholder: "Motif de protection", addProtectedCreator: "Protéger le créateur", emptySpreadsheet: "Aucune feuille lisible.", missingCreatorIdentity: "Indiquez creator_open_id ou username.", duplicateCreator: "Créateur en double.", unknownDeveloper: "Le BD « {{name}} » n'existe pas.", protectionsImported: "{{count}} créateurs protégés importés.", confirmBoundary: "J'ai vérifié la liste. L'équipe IA peut gérer les relations non protégées et sans BD humain.", completeSetup: "Terminer et activer l'IA", onboardingCompleted: "Configuration terminée.",
} as const;

const id = {
  eyebrow: "Operasi afiliasi", title: "Tim & kanal", subtitle: "Tetapkan relasi kreator dan akun kontak kepada penanggung jawab.", addDeveloper: "Tambah BD", aiTeam: "Tim AI", aiTeamHint: "Relasi belum ditugaskan", aiTeamDescription: "Tim AI menangani relasi yang memenuhi syarat tanpa BD manusia.", businessDeveloper: "Business developer", virtualOwner: "Pemilik default", developerHint: "Mode dan instruksi BD berlaku untuk semua kreator yang ditugaskan.", roster: "Penanggung jawab", workMode: "Mode kerja", aiAssisted: "Dibantu AI", humanOnly: "Hanya manusia", aiManaged: "Dikelola AI", acceptingCreators: "Menerima kreator baru", whatsappAccounts: "Akun WhatsApp", emailAccounts: "Akun email", channels: "Kanal", connectChannel: "Hubungkan kanal", noChannels: "Belum ada akun yang ditugaskan.", unnamedAccount: "Akun tanpa nama", workingStyle: "Gaya kerja", workingStylePlaceholder: "Jelaskan nada, prioritas, negosiasi, dan serah terima.", regions: "Wilayah", name: "Nama", newDeveloper: "BD baru", nameRequired: "Masukkan nama BD.", saved: "Pengaturan tersimpan.", archive: "Arsipkan", archiveConfirm: "Arsipkan {{name}}? Pindahkan kreator dan akunnya dahulu.", archived: "BD diarsipkan.", transferConfirm: "Pindahkan akun ini? Kanal dan pekerjaan terkait akan diperbarui.", accountMoved: "Pemilik akun diperbarui.", onboardingStep: "Penyiapan afiliasi", onboardingTitle: "Lindungi relasi BD sebelum AI dimulai", onboardingHint: "Impor kreator yang sudah dikelola. Relasi lain dapat ditangani tim AI.", downloadTemplate: "Unduh templat", importProtected: "Impor kreator terlindungi", importPreview: "Pratinjau impor", importValid: "Impor {{count}} baris valid", protectedOnly: "Hanya dilindungi", ready: "Siap", creatorIdentity: "Identitas kreator", creatorIdentityPlaceholder: "@username atau Open ID", assignDeveloper: "BD penanggung jawab", note: "Catatan", notePlaceholder: "Alasan perlindungan", addProtectedCreator: "Lindungi kreator", emptySpreadsheet: "Tidak ada lembar yang dapat dibaca.", missingCreatorIdentity: "Isi creator_open_id atau username.", duplicateCreator: "Kreator duplikat.", unknownDeveloper: "BD “{{name}}” tidak ada.", protectionsImported: "{{count}} kreator terlindungi diimpor.", confirmBoundary: "Saya telah meninjau daftar. Tim AI boleh menangani relasi yang tidak dilindungi dan tanpa BD manusia.", completeSetup: "Selesaikan dan aktifkan AI", onboardingCompleted: "Penyiapan selesai.",
} as const;

const it = {
  eyebrow: "Operazioni affiliate", title: "Team e canali", subtitle: "Assegna relazioni e account di contatto ai responsabili.", addDeveloper: "Aggiungi BD", aiTeam: "Team AI", aiTeamHint: "Relazioni non assegnate", aiTeamDescription: "Il team AI gestisce le relazioni idonee senza BD umano.", businessDeveloper: "Business developer", virtualOwner: "Responsabile predefinito", developerHint: "Modalità e istruzioni del BD si applicano ai creator assegnati.", roster: "Responsabili", workMode: "Modalità di lavoro", aiAssisted: "Assistito da AI", humanOnly: "Solo umano", aiManaged: "Gestito da AI", acceptingCreators: "Accetta nuovi creator", whatsappAccounts: "Account WhatsApp", emailAccounts: "Account email", channels: "Canali", connectChannel: "Collega canale", noChannels: "Nessun account assegnato.", unnamedAccount: "Account senza nome", workingStyle: "Stile di lavoro", workingStylePlaceholder: "Descrivi tono, priorità, negoziazione e passaggi di consegna.", regions: "Regioni", name: "Nome", newDeveloper: "Nuovo BD", nameRequired: "Inserisci il nome del BD.", saved: "Impostazioni salvate.", archive: "Archivia", archiveConfirm: "Archiviare {{name}}? Riassegna prima creator e account.", archived: "BD archiviato.", transferConfirm: "Spostare questo account? Canali e lavori collegati verranno aggiornati.", accountMoved: "Responsabile aggiornato.", onboardingStep: "Configurazione affiliate", onboardingTitle: "Proteggi le relazioni esistenti prima dell'AI", onboardingHint: "Importa i creator già gestiti. Gli altri potranno essere gestiti dal team AI.", downloadTemplate: "Scarica modello", importProtected: "Importa creator protetti", importPreview: "Anteprima", importValid: "Importa {{count}} righe valide", protectedOnly: "Solo protetto", ready: "Pronto", creatorIdentity: "Identità creator", creatorIdentityPlaceholder: "@username o Open ID", assignDeveloper: "BD responsabile", note: "Nota", notePlaceholder: "Motivo della protezione", addProtectedCreator: "Proteggi creator", emptySpreadsheet: "Nessun foglio leggibile.", missingCreatorIdentity: "Inserisci creator_open_id o username.", duplicateCreator: "Creator duplicato.", unknownDeveloper: "Il BD “{{name}}” non esiste.", protectionsImported: "Importati {{count}} creator protetti.", confirmBoundary: "Ho verificato l'elenco. Il team AI può gestire relazioni non protette e senza BD umano.", completeSetup: "Completa e attiva AI", onboardingCompleted: "Configurazione completata.",
} as const;

const th = {
  eyebrow: "งาน Affiliate", title: "ทีมและช่องทาง", subtitle: "มอบหมายความสัมพันธ์และบัญชีติดต่อให้ผู้รับผิดชอบ", addDeveloper: "เพิ่ม BD", aiTeam: "ทีม AI", aiTeamHint: "ความสัมพันธ์ที่ยังไม่มอบหมาย", aiTeamDescription: "ทีม AI ดูแลความสัมพันธ์ที่เข้าเกณฑ์และไม่มี BD", businessDeveloper: "Business developer", virtualOwner: "ผู้รับผิดชอบเริ่มต้น", developerHint: "โหมดและคำแนะนำของ BD ใช้กับครีเอเตอร์ที่ได้รับมอบหมาย", roster: "ผู้รับผิดชอบ", workMode: "โหมดการทำงาน", aiAssisted: "AI ช่วยงาน", humanOnly: "คนดูแลเท่านั้น", aiManaged: "AI ดูแล", acceptingCreators: "รับครีเอเตอร์ใหม่", whatsappAccounts: "บัญชี WhatsApp", emailAccounts: "บัญชีอีเมล", channels: "ช่องทาง", connectChannel: "เชื่อมต่อช่องทาง", noChannels: "ยังไม่มีบัญชีที่มอบหมาย", unnamedAccount: "บัญชีไม่มีชื่อ", workingStyle: "รูปแบบการทำงาน", workingStylePlaceholder: "ระบุน้ำเสียง ลำดับความสำคัญ การเจรจา และการส่งต่องาน", regions: "ภูมิภาค", name: "ชื่อ", newDeveloper: "BD ใหม่", nameRequired: "กรุณาใส่ชื่อ BD", saved: "บันทึกแล้ว", archive: "เก็บถาวร", archiveConfirm: "เก็บ {{name}} หรือไม่ โปรดย้ายครีเอเตอร์และบัญชีก่อน", archived: "เก็บ BD แล้ว", transferConfirm: "ย้ายบัญชีนี้หรือไม่ ช่องทางและงานที่เกี่ยวข้องจะถูกรีเฟรช", accountMoved: "อัปเดตผู้รับผิดชอบแล้ว", onboardingStep: "ตั้งค่า Affiliate", onboardingTitle: "ปกป้องความสัมพันธ์เดิมก่อนเปิด AI", onboardingHint: "นำเข้าครีเอเตอร์ที่ทีมดูแลอยู่ ความสัมพันธ์อื่นสามารถให้ทีม AI ดูแลได้", downloadTemplate: "ดาวน์โหลดแม่แบบ", importProtected: "นำเข้าครีเอเตอร์ที่ปกป้อง", importPreview: "ตัวอย่างนำเข้า", importValid: "นำเข้า {{count}} แถว", protectedOnly: "ปกป้องเท่านั้น", ready: "พร้อม", creatorIdentity: "ตัวตนครีเอเตอร์", creatorIdentityPlaceholder: "@username หรือ Open ID", assignDeveloper: "BD ผู้รับผิดชอบ", note: "หมายเหตุ", notePlaceholder: "เหตุผลที่ปกป้อง", addProtectedCreator: "เพิ่มครีเอเตอร์", emptySpreadsheet: "ไม่พบชีตที่อ่านได้", missingCreatorIdentity: "กรอก creator_open_id หรือ username", duplicateCreator: "ครีเอเตอร์ซ้ำ", unknownDeveloper: "ไม่พบ BD “{{name}}”", protectionsImported: "นำเข้า {{count}} ครีเอเตอร์แล้ว", confirmBoundary: "ฉันตรวจสอบรายชื่อแล้ว ทีม AI สามารถดูแลความสัมพันธ์ที่ไม่ถูกปกป้องและไม่มี BD ได้", completeSetup: "เสร็จสิ้นและเปิด AI", onboardingCompleted: "ตั้งค่าเสร็จแล้ว",
} as const;

export const AFFILIATE_TEAM_TRANSLATIONS = {
  en: { nav: { affiliateTeam: "Team & channels" }, ecommerce: { affiliateTeam: en, affiliateWorkspace: { relationshipOwner: "Relationship owner", relationshipOwnerLabel: "Responsible team", relationshipAiParticipation: "AI participation", relationshipAiEnabled: "AI enabled", relationshipProtected: "Protected", relationshipOwnerChangeConfirm: "Change the owner? Pending work may be refreshed against the new BD configuration.", relationshipAiChangeConfirm: "Change AI participation? Pending work may be invalidated and rebuilt.", relationshipHumanOnlyHint: "{{name}} is human-only, so AI will not run for this relationship." } } },
  zh: { nav: { affiliateTeam: "团队与渠道" }, ecommerce: { affiliateTeam: zh, affiliateWorkspace: { relationshipOwner: "达人关系负责人", relationshipOwnerLabel: "负责团队", relationshipAiParticipation: "AI 参与", relationshipAiEnabled: "允许 AI", relationshipProtected: "受保护", relationshipOwnerChangeConfirm: "更换负责人？待处理工作可能会根据新 BD 配置重新生成。", relationshipAiChangeConfirm: "修改 AI 参与状态？现有待办可能会失效并重新生成。", relationshipHumanOnlyHint: "{{name}} 设置为仅人工处理，因此该达人关系不会触发 AI。" } } },
  de: { nav: { affiliateTeam: "Team & Kanäle" }, ecommerce: { affiliateTeam: de, affiliateWorkspace: { relationshipOwner: "Beziehungsverantwortlicher", relationshipOwnerLabel: "Zuständiges Team", relationshipAiParticipation: "KI-Beteiligung", relationshipAiEnabled: "KI aktiviert", relationshipProtected: "Geschützt", relationshipOwnerChangeConfirm: "Verantwortlichen ändern? Offene Arbeit kann aktualisiert werden.", relationshipAiChangeConfirm: "KI-Beteiligung ändern? Offene Arbeit kann neu erstellt werden.", relationshipHumanOnlyHint: "{{name}} arbeitet nur manuell; für diese Beziehung startet keine KI." } } },
  es: { nav: { affiliateTeam: "Equipo y canales" }, ecommerce: { affiliateTeam: es, affiliateWorkspace: { relationshipOwner: "Responsable de la relación", relationshipOwnerLabel: "Equipo responsable", relationshipAiParticipation: "Participación de IA", relationshipAiEnabled: "IA activada", relationshipProtected: "Protegida", relationshipOwnerChangeConfirm: "¿Cambiar responsable? El trabajo pendiente puede actualizarse.", relationshipAiChangeConfirm: "¿Cambiar la participación de IA? El trabajo pendiente puede regenerarse.", relationshipHumanOnlyHint: "{{name}} es solo humano; la IA no se ejecutará." } } },
  fr: { nav: { affiliateTeam: "Équipe et canaux" }, ecommerce: { affiliateTeam: fr, affiliateWorkspace: { relationshipOwner: "Responsable de la relation", relationshipOwnerLabel: "Équipe responsable", relationshipAiParticipation: "Participation de l'IA", relationshipAiEnabled: "IA activée", relationshipProtected: "Protégée", relationshipOwnerChangeConfirm: "Changer le responsable ? Le travail en attente peut être actualisé.", relationshipAiChangeConfirm: "Modifier la participation de l'IA ? Le travail peut être reconstruit.", relationshipHumanOnlyHint: "{{name}} est en mode humain uniquement ; l'IA ne sera pas lancée." } } },
  id: { nav: { affiliateTeam: "Tim & kanal" }, ecommerce: { affiliateTeam: id, affiliateWorkspace: { relationshipOwner: "Pemilik relasi", relationshipOwnerLabel: "Tim penanggung jawab", relationshipAiParticipation: "Partisipasi AI", relationshipAiEnabled: "AI aktif", relationshipProtected: "Dilindungi", relationshipOwnerChangeConfirm: "Ubah penanggung jawab? Pekerjaan tertunda dapat diperbarui.", relationshipAiChangeConfirm: "Ubah partisipasi AI? Pekerjaan tertunda dapat dibuat ulang.", relationshipHumanOnlyHint: "{{name}} hanya manusia; AI tidak akan berjalan." } } },
  it: { nav: { affiliateTeam: "Team e canali" }, ecommerce: { affiliateTeam: it, affiliateWorkspace: { relationshipOwner: "Responsabile della relazione", relationshipOwnerLabel: "Team responsabile", relationshipAiParticipation: "Partecipazione AI", relationshipAiEnabled: "AI attiva", relationshipProtected: "Protetta", relationshipOwnerChangeConfirm: "Cambiare responsabile? Il lavoro in attesa può essere aggiornato.", relationshipAiChangeConfirm: "Cambiare la partecipazione AI? Il lavoro può essere rigenerato.", relationshipHumanOnlyHint: "{{name}} è solo umano; l'AI non verrà eseguita." } } },
  th: { nav: { affiliateTeam: "ทีมและช่องทาง" }, ecommerce: { affiliateTeam: th, affiliateWorkspace: { relationshipOwner: "ผู้รับผิดชอบความสัมพันธ์", relationshipOwnerLabel: "ทีมที่รับผิดชอบ", relationshipAiParticipation: "การใช้ AI", relationshipAiEnabled: "เปิด AI", relationshipProtected: "ปกป้อง", relationshipOwnerChangeConfirm: "เปลี่ยนผู้รับผิดชอบหรือไม่ งานที่ค้างอาจถูกรีเฟรช", relationshipAiChangeConfirm: "เปลี่ยนการใช้ AI หรือไม่ งานที่ค้างอาจถูกสร้างใหม่", relationshipHumanOnlyHint: "{{name}} ตั้งเป็นคนดูแลเท่านั้น จึงไม่เรียกใช้ AI" } } },
} as const;
